export const ORIGINAL_FLOW_BY_BEAT = {
  carbo_contract: {
    chapter: 'Chapter I',
    title: 'Witt Forest → Carbo Village → Church → Inn',
    originalRoute: [
      'Witt Forest',
      'Carbo Village (first visit)',
      'Church of Granas',
      'Carbo Inn',
    ],
    townSubLocations: ['Church', 'Inn', 'General Store', 'village houses'],
    dungeonSubStages: [],
    fidelityGoals: [
      'Сильнее выделить вступительный village loop как спокойное “до катастрофы”.',
      'Дать ещё больше локальных реплик в церкви и трактире.',
    ],
  },
  garmia_failure: {
    chapter: 'Chapter I',
    title: 'Black Forest → Garmia Tower floors → Top Floor',
    originalRoute: [
      'The Black Forest',
      'Garmia Tower 1 Floor',
      'Garmia Tower 2 Floor',
      'Garmia Tower 3 Floor',
      'Garmia Tower Top Floor',
    ],
    townSubLocations: [],
    dungeonSubStages: ['Lower floors', 'Upper floor', 'Broken window escape', 'Top-floor catastrophe'],
    fidelityGoals: [
      'Сделать floor-to-floor feel заметнее.',
      'Усилить ощущение аварийной эвакуации после верхней площадки.',
    ],
  },
  millenia_first_attack: {
    chapter: 'Chapter I',
    title: 'Carbo second visit → impossible Millenia pressure',
    originalRoute: [
      'Carbo Village (second visit)',
      'Church / village aftermath',
      'Night sequence',
      'Millenia confrontation',
      'Inn aftermath',
    ],
    townSubLocations: ['Church aftermath', 'Inn night scene'],
    dungeonSubStages: [],
    fidelityGoals: [
      'Сделать ночную атаку ещё более отдельным сценическим эпизодом.',
      'Добавить больше “деревня ломается ночью” в подаче setpiece.',
    ],
  },
  agear_roan: {
    chapter: 'Chapter I',
    title: 'Inor Mountains → Agear → Durham Cave',
    originalRoute: [
      'Inor Mountains 1',
      'Inor Mountains 2',
      'Agear Town',
      'Durham Cave 1',
      'Durham Cave 2',
      'Durham Cave Depths',
    ],
    townSubLocations: ['Agear Inn', 'Guard Tent'],
    dungeonSubStages: ['Bridge / lever section', 'Roan rescue', 'Depths boss threshold'],
    fidelityGoals: [
      'Разделить путь через Durham Cave ещё ярче по этапам.',
      'Подчеркнуть переход от разрушенного города к спасению Роана.',
    ],
  },
  liligue_and_mareg: {
    chapter: 'Chapter I',
    title: 'Baked Plains → Liligue → Liligue Cave → Temple Ruins',
    originalRoute: [
      'Baked Plains 1',
      'Baked Plains 2',
      'Baked Plains 3',
      'Liligue City',
      'Liligue Cave 1',
      'Liligue Cave 2',
      'Liligue Cave 3',
      'Temple Ruins',
    ],
    townSubLocations: ['Gadan House', 'Church', 'Skyway side of town'],
    dungeonSubStages: ['Seal switches', 'Temple approach', 'Tongue arena'],
    fidelityGoals: [
      'Больше бытовой жизни инженеров Лилига.',
      'Чётче показать руинные механизмы как часть пути к Tongue of Valmar.',
    ],
  },
  st_heim_zera: {
    chapter: 'Chapter II',
    title: 'Lumir / Mirumu / St. Heim audience chain',
    originalRoute: [
      'Lumir Forest',
      'Garden of Dreams',
      'Mirumu Village',
      'Mysterious Fissure',
      "Aira's Space",
      'St. Heim Mountains',
      'St. Heim Papal State',
      'Audience Chamber',
      'Library',
      'Guestroom',
      'Balcony',
      'Audience Chamber (second visit)',
    ],
    townSubLocations: ['Inn', 'Audience Chamber', 'Library', 'Guestroom', 'Balcony'],
    dungeonSubStages: ['Aira rescue flow', 'St. Heim arrival', 'audience / library / balcony loop'],
    fidelityGoals: [
      'Добавить больше церковных NPC-сцен и формальной торжественности.',
      'Сильнее отделить “священный фасад” от скрытой лжи Зеры.',
    ],
  },
  cyrum_and_claws: {
    chapter: 'Chapter II',
    title: 'Pilgrim Road / Raul Hills / Cyrum / Secret Passage / Underground Plant',
    originalRoute: [
      'Pilgrim Road',
      'Raul Hills 1',
      'Raul Hills 2',
      'Cyrum Kingdom',
      'Castle Square',
      'Port',
      'Cyrum Castle Secret Passage',
      'Underground Plant 1',
      'Underground Plant 2',
      'Underground Plant 3',
      'Underground Control Room',
    ],
    townSubLocations: ['Inn', 'Castle Square', 'Hemble tent', 'Port', 'King’s Chamber'],
    dungeonSubStages: ['Secret passage levers', 'Plant terminals', 'Pipe route', 'Control Room'],
    fidelityGoals: [
      'Поднять уникальность замковой и заводской части.',
      'Сильнее развести city episode и underground infiltration.',
    ],
  },
  garlan_return: {
    chapter: 'Chapter III',
    title: 'Ceceile Reef → Garlan return',
    originalRoute: [
      'Ceceile Reef',
      'Garlan Village',
      "Ryudo's House",
      'Garlan Inn',
    ],
    townSubLocations: ['Ryudo’s House', 'Inn', 'Village Tombs'],
    dungeonSubStages: [],
    fidelityGoals: [
      'Больше hostile-homecoming атмосферы у жителей.',
      'Чётче давить на память и вину Рюдо до выхода к Грайлу.',
    ],
  },
  melfice_duel: {
    chapter: 'Chapter III',
    title: 'Grail Mountain → Shrine → Plateau of Memories',
    originalRoute: [
      'Grail Mountain Road 1',
      'Grail Mountain Road 2',
      'Grail Mountain Shrine',
      'Plateau of Memories',
    ],
    townSubLocations: [],
    dungeonSubStages: ['Climb', 'Shrine revelation', 'Plateau threshold', 'Duel'],
    fidelityGoals: [
      'Сделать climb/shrine/plateau ещё более режиссёрски разными.',
      'Усилить переход от village trauma к личной дуэли.',
    ],
  },
  nanan_and_cyclone: {
    chapter: 'Chapter III',
    title: 'Ghoss Forest → Nanan → Great Rift → Demons Law',
    originalRoute: [
      'Ghoss Forest West',
      'Nanan Village',
      'Ghoss Forest East',
      'The Great Rift 1',
      'The Great Rift 2',
      'The Great Rift 3',
      "Demon's Law",
    ],
    townSubLocations: ['Nanan Village'],
    dungeonSubStages: ['Storm path', 'rift crossing', 'Demon’s Law access'],
    fidelityGoals: [
      'Усилить ощущение циклонного перехода к Гранасаберу.',
      'Сделать Great Rift ещё более “edge of the world”.',
    ],
  },
  granasaber_ship: {
    chapter: 'Chapter III',
    title: 'Demons Law → Valmar’s Body → true Granasaber',
    originalRoute: [
      "Demon's Law Control Room",
      "Valmar's Body Point of Entry",
      "Valmar's Body Tentacle Passage",
      "Valmar's Body Vein Passage",
      "Valmar's Body Spherical Room",
      "Valmar's Body Artery Passage",
      "Valmar's Body Core",
      'Granasaber reveal',
    ],
    townSubLocations: [],
    dungeonSubStages: ['Control Room push', 'Organic corridors', 'Body core', 'Ancient-machine reveal'],
    fidelityGoals: [
      'Сделать reveal древнего корабля ещё более уникальным setpiece.',
      'Сильнее развести Body traversal и myth-break момент.',
    ],
  },
  cathedral_massacre: {
    chapter: 'Chapter IV',
    title: 'St. Heim second visit / Day of Darkness',
    originalRoute: [
      'St. Heim Papal State (second visit)',
      'Granas Cathedral',
      'Holy Room',
      'Late cathedral routes',
    ],
    townSubLocations: ['Cathedral Lobby', 'Audience spaces', 'late cathedral rooms'],
    dungeonSubStages: ['Massacre entry', 'late cathedral push'],
    fidelityGoals: [
      'Поднять ощущение collapse state ещё выше.',
      'Добавить больше room-specific late St. Heim tension.',
    ],
  },
  zera_revealed: {
    chapter: 'Chapter IV',
    title: 'Forbidden Room / Zera reveal chain',
    originalRoute: [
      'Late Granas Cathedral',
      'Forbidden Room',
      'Zera reveal corridor',
    ],
    townSubLocations: ['Forbidden Room', 'late audience sequence'],
    dungeonSubStages: ['Reveal access', 'truth exposure'],
    fidelityGoals: [
      'Чётче развести Day of Darkness и reveal Zera как две разные поздние фазы.',
      'Добавить больше переходной церковной режиссуры.',
    ],
  },
  moon_assault: {
    chapter: 'Chapter IV',
    title: 'Valmar’s Moon → Valmar’s Womb',
    originalRoute: [
      "Valmar's Moon Surface",
      "Valmar's Moon 1",
      "Valmar's Moon 2",
      "Valmar's Moon 3",
      "Valmar's Womb",
    ],
    townSubLocations: [],
    dungeonSubStages: ['Surface push', 'mid-moon progression', 'Womb approach'],
    fidelityGoals: [
      'Делать ещё сильнее ощущение осады и жертвы Марега.',
      'Добавить больше late-moon room identity.',
    ],
  },
  cyrum_defense: {
    chapter: 'Chapter IV',
    title: 'Late Cyrum war-state',
    originalRoute: [
      'Cyrum Kingdom South',
      'Cyrum Kingdom (late)',
      'Raul Hills war front',
    ],
    townSubLocations: ['late square', 'late port', 'war room mood'],
    dungeonSubStages: ['South front', 'war-room organization'],
    fidelityGoals: [
      'Добавить больше ощущения фронта и мобилизации.',
      'Сильнее показать late Cyrum как совсем другую версию хаба.',
    ],
  },
  birthplace_descent: {
    chapter: 'Chapter IV',
    title: 'Birthplace of the Gods 1/2/3',
    originalRoute: [
      'Cyrum Kingdom South',
      'Birthplace of the Gods 1',
      'Birthplace of the Gods 2',
      'Birthplace of the Gods 3',
    ],
    townSubLocations: [],
    dungeonSubStages: ['Truth discovery', 'blue / yellow / red mechanisms'],
    fidelityGoals: [
      'Поднять room-specific puzzle feel.',
      'Сильнее развести myth-reversal и traversal.',
    ],
  },
  inner_trial: {
    chapter: 'Chapter IV',
    title: 'Inner Trial / acceptance of self',
    originalRoute: [
      'Inner Trial threshold',
      'Shadow confrontation',
      'Acceptance of self',
    ],
    townSubLocations: [],
    dungeonSubStages: ['Acceptance trigger', 'Shadow duel', 'True Granasaber turn'],
    fidelityGoals: [
      'Сделать phase/visual language ещё более отличной от обычного боя.',
      'Усилить психологическую, а не только боевую идентичность.',
    ],
  },
  zera_inside_valmar: {
    chapter: 'Chapter IV',
    title: 'New Valmar 1/2/3 → Room of Chaos',
    originalRoute: [
      'New Valmar 1',
      'New Valmar 2',
      'New Valmar 3',
      'Room of Chaos',
    ],
    townSubLocations: ['Room of Chaos'],
    dungeonSubStages: ['Outer shell', 'lie-layer', 'chaos room access'],
    fidelityGoals: [
      'Сделать New Valmar ещё более чужим и органически лживым.',
      'Усилить ощущение ложных форм и последней внутренней войны с Зерой.',
    ],
  },
  true_finale: {
    chapter: 'Chapter IV',
    title: 'New Valmar Core / final judgement',
    originalRoute: [
      'New Valmar Core',
      'Final core threshold',
      'Final confrontation',
    ],
    townSubLocations: ['Core chamber'],
    dungeonSubStages: ['Core access', 'Human-choice finale'],
    fidelityGoals: [
      'Усилить постановку финального ядра и последней дороги.',
      'Сделать финал ещё сильнее как идеологический приговор ложным богам.',
    ],
  },
};

export function getOriginalFlowForBeat(beatId) {
  return ORIGINAL_FLOW_BY_BEAT[beatId] ?? null;
}
