const TOWN = 'town';
const FIELD = 'field';
const DUNGEON = 'dungeon';
const INTERIOR = 'interior';
const SPECIAL = 'special';

function loc(id, config) {
  return {
    id,
    major: config.major ?? false,
    facilities: config.facilities ?? [],
    chapterIds: config.chapterIds ?? [],
    exits: config.exits ?? [],
    ...config,
  };
}

export const WORLD_CHAPTERS = {
  chapter_1: {
    id: 'chapter_1',
    title: 'Южная Силезия и путь до Лилига',
    summary: 'От Карбо и башни Гармии до Агира, Дархэмской пещеры и Лилига.',
  },
  chapter_2: {
    id: 'chapter_2',
    title: 'Восточная Силезия, Мирума и церковный центр',
    summary: 'Люмир, Мирума, Сент-Хейм, Раул Хиллс и Цайрум.',
  },
  chapter_3: {
    id: 'chapter_3',
    title: 'Охота за Гранасабером',
    summary: 'Сесильский риф, Гарлан, Грайл, Нанан, Великий Разлом и Тело Вальмара.',
  },
  chapter_4: {
    id: 'chapter_4',
    title: 'Эндгейм: Луна, Исток богов и Новый Вальмар',
    summary: 'Повторный Сент-Хейм, Луна Вальмара, оборона Цайрума, Исток богов и финальный данж.',
  },
};

export const ITEM_CATALOG = [
  { key: 'medicinalHerb', label: 'Medicinal Herb', kind: 'healing', description: 'Базовое лечение одного союзника.' },
  { key: 'antidote', label: 'Poison Antidote', kind: 'status', description: 'Снимает poison.' },
  { key: 'woundSalve', label: 'Wound Salve', kind: 'healing', description: 'Усиленное лечение одного союзника.' },
  { key: 'healingHerb', label: 'Healing Herb', kind: 'healing', description: 'Небольшое лечение всей группы.' },
  { key: 'eyeDrops', label: 'Eye Drops', kind: 'status', description: 'Снимает sleep.' },
  { key: 'moveBlessing', label: 'Move Blessing', kind: 'status', description: 'Снимает move-block.' },
  { key: 'magicBlessing', label: 'Magic Blessing', kind: 'status', description: 'Снимает magic-block.' },
  { key: 'panacea', label: 'Panacea', kind: 'status', description: 'Снимает все основные статусы с одного союзника.' },
  { key: 'yomisElixir', label: "Yomi's Elixir", kind: 'revive', description: 'Воскрешает павшего союзника.' },
  { key: 'blueberry', label: 'Blueberry', kind: 'sp', description: 'Восстанавливает SP одному союзнику.' },
  { key: 'lumirFlower', label: 'Lumir Flower', kind: 'mp', description: 'Восстанавливает MP одному союзнику.' },
  { key: 'healingIncense', label: 'Healing Incense', kind: 'healing', description: 'Сильное лечение всей группы.' },
  { key: 'scarletPotion', label: 'Scarlet Potion', kind: 'healing', description: 'Легендарный алый эликсир: сильное лечение одного союзника.' },
  { key: 'purifyingHerb', label: 'Purifying Herb', kind: 'status', description: 'Снимает poison и немного лечит.' },
  { key: 'poffNut', label: 'Poff Nut', kind: 'healing', description: 'Орех, который восстанавливает немного HP.' },
  { key: 'seedOfLife', label: 'Seed of Life', kind: 'healing', description: 'Семя жизни: заметное лечение одного союзника.' },
  { key: 'seedOfPsyche', label: 'Seed of Psyche', kind: 'sp', description: 'Семя духа: восстанавливает SP.' },
  { key: 'seedOfMagic', label: 'Seed of Magic', kind: 'mp', description: 'Семя магии: восстанавливает MP.' },
  { key: 'manaCrystal', label: 'Mana Crystal', kind: 'mp', description: 'Кристалл маны: много MP одному союзнику.' },
  { key: 'caterpillarSoup', label: 'Caterpillar Soup', kind: 'healing', description: 'Гусеничный суп: лечение всей группы и снятие яда.' },
  { key: 'paralysisSalve', label: 'Paralysis Salve', kind: 'status', description: 'Снимает move-block / паралич.' },
  { key: 'firebomb', label: 'Firebomb', kind: 'offensive', description: 'Огненная бомба по одной цели.' },
  { key: 'mogayBomb', label: 'Mogay Bomb', kind: 'offensive', description: 'Взрывчатка могеев по всем врагам.' },
  { key: 'handGrenade', label: 'Hand Grenade', kind: 'offensive', description: 'Ручная граната по всем врагам.' },
  { key: 'meteorScroll', label: 'Meteor Scroll', kind: 'offensive', description: 'Свиток метеоритного дождя по всем врагам.' },
  { key: 'whirlwindScroll', label: 'Whirlwind Scroll', kind: 'offensive', description: 'Свиток ураганного ветра по всем врагам.' },
  { key: 'scrollOfAlheal', label: 'Scroll of Alheal', kind: 'healing', description: 'Свиток массового лечения всей группы.' },
  { key: 'sympathyNut', label: 'Sympathy Nut', kind: 'healing', description: 'Орех сочувствия: заметное лечение одного союзника.' },
  { key: 'seedOfRunning', label: 'Seed of Running', kind: 'sp', description: 'Семя бега: восстанавливает немного SP.' },

  { key: 'healingFruit', label: 'Healing Fruit', kind: 'healing', description: 'Вкусный целебный фрукт: заметное лечение одного союзника.' },
  { key: 'potionOfAzure', label: 'Potion of Azure', kind: 'healing', description: 'Лазурное зелье: сильное лечение всей группы.' },
  { key: 'tortesReedpipe', label: 'Torte\'s Reedpipe', kind: 'status', description: 'Дудочка Торте: будит союзника ото сна.' },
  { key: 'smellingSalts', label: 'Smelling Salts', kind: 'status', description: 'Нюхательная соль: снимает сон и паралич.' },
  { key: 'blessingScroll', label: 'Blessing Scroll', kind: 'status', description: 'Свиток благословения: снимает все статусы с одного союзника.' },
  { key: 'vaccine', label: 'Vaccine', kind: 'status', description: 'Вакцина: снимает яд.' },
  { key: 'holyAshes', label: 'Holy Ashes', kind: 'revive', description: 'Святая зола: воскрешает павшего союзника.' },
  { key: 'myriadPowerNut', label: 'Myriad Power Nut', kind: 'sp', description: 'Орех силы: восстанавливает SP.' },
  { key: 'patienceNut', label: 'Patience Nut', kind: 'healing', description: 'Орех терпения: небольшое лечение.' },
  { key: 'swiftnessNut', label: 'Swiftness Nut', kind: 'sp', description: 'Орех скорости: восстанавливает SP.' },
  { key: 'slowpokeNut', label: 'Slowpoke Nut', kind: 'healing', description: 'Орех медлительности: крошечное лечение.' },
  { key: 'dynamite', label: 'Dynamite', kind: 'offensive', description: 'Динамит: огненный урон по всем врагам.' },
  { key: 'hyperMogayBomb', label: 'Hyper Mogay Bomb', kind: 'offensive', description: 'Гипер-бомба могеев: сильный огненный урон по всем.' },
  { key: 'superMogayBomb', label: 'Super Mogay Bomb', kind: 'offensive', description: 'Супер-бомба могеев: мощнейший огненный урон по всем.' },
  { key: 'redGoblinToad', label: 'Red Goblin Toad', kind: 'offensive', description: 'Красная жаба: огненный урон по всем врагам.' },
  { key: 'sandmanWhiskers', label: 'Sandman Whiskers', kind: 'sp', description: 'Усы песчаного духа: восстанавливает SP.' },
  { key: 'spiderweb', label: 'Spiderweb', kind: 'offensive', description: 'Паутина: блокирует движение одной цели.' },
  { key: 'toadOil', label: 'Toad Oil', kind: 'mp', description: 'Жабье масло: восстанавливает MP.' },
  { key: 'magicalMedicine', label: 'Magical Medicine', kind: 'healing', description: 'Магическое снадобье: сильное лечение всей группы.' },
  { key: 'goldenPotion', label: 'Golden Potion', kind: 'healing', description: 'Золотое зелье: очень сильное лечение всей группы.' },
  { key: 'heroElixir', label: 'Hero\'s Elixir', kind: 'healing', description: 'Эликсир героя: полное лечение и снятие статусов.' },
  { key: 'demonAsh', label: 'Demon Ash', kind: 'offensive', description: 'Пепел демона: урон одной цели.' },
  { key: 'redBirdStone', label: 'Red Bird Stone', kind: 'offensive', description: 'Камень красной птицы: огненный урон одной цели.' },
  { key: 'icefangStone', label: 'Icefang Stone', kind: 'offensive', description: 'Камень ледяного клыка: ледяной урон одной цели.' },
  { key: 'electrumStone', label: 'Electrum Stone', kind: 'offensive', description: 'Электрумовый камень: молниевый урон одной цели.' },
  { key: 'galeStone', label: 'Gale Stone', kind: 'offensive', description: 'Камень урагана: ветровой урон по всем врагам.' },
  { key: 'flameStone', label: 'Flame Stone', kind: 'offensive', description: 'Камень пламени: огненный урон одной цели.' },
  { key: 'quakeStone', label: 'Quake Stone', kind: 'offensive', description: 'Камень землетрясения: земляной урон по всем врагам.' },
];

export const SHOP_CATALOG = [
  { id: 'herb', label: 'Medicinal Herb', key: 'medicinalHerb', price: 30, amount: 1, description: 'Базовое лечение в бою.' },
  { id: 'antidote', label: 'Poison Antidote', key: 'antidote', price: 20, amount: 1, description: 'Снятие яда в бою.' },
  { id: 'wound_salve', label: 'Wound Salve', key: 'woundSalve', price: 65, amount: 1, description: 'Усиленное лечение одного союзника.' },
  { id: 'healing_herb', label: 'Healing Herb', key: 'healingHerb', price: 90, amount: 1, description: 'Лёгкое массовое лечение партии.' },
  { id: 'eye_drops', label: 'Eye Drops', key: 'eyeDrops', price: 18, amount: 1, description: 'Снимает sleep.' },
  { id: 'move_blessing', label: 'Move Blessing', key: 'moveBlessing', price: 45, amount: 1, description: 'Снимает move-block.' },
  { id: 'magic_blessing', label: 'Magic Blessing', key: 'magicBlessing', price: 45, amount: 1, description: 'Снимает magic-block.' },
  { id: 'panacea', label: 'Panacea', key: 'panacea', price: 160, amount: 1, description: 'Снимает все ключевые статусы.' },
  { id: 'yomis_elixir', label: "Yomi's Elixir", key: 'yomisElixir', price: 240, amount: 1, description: 'Воскрешает павшего союзника.' },
  { id: 'blueberry', label: 'Blueberry', key: 'blueberry', price: 55, amount: 1, description: 'Восстанавливает SP.' },
  { id: 'lumir_flower', label: 'Lumir Flower', key: 'lumirFlower', price: 70, amount: 1, description: 'Восстанавливает MP.' },
  { id: 'healing_incense', label: 'Healing Incense', key: 'healingIncense', price: 220, amount: 1, description: 'Массовое лечение группы.' },
  { id: 'field_pack', label: 'Field Pack', bundle: { medicinalHerb: 2, antidote: 1, eyeDrops: 1 }, price: 90, description: 'Небольшой походный набор на дорогу.' },
  { id: 'restoration_pack', label: 'Restoration Pack', bundle: { woundSalve: 1, moveBlessing: 1, magicBlessing: 1 }, price: 150, description: 'Набор на тяжёлые сюжетные стычки.' },
  { id: 'rescue_pack', label: 'Rescue Pack', bundle: { yomisElixir: 1, panacea: 1, blueberry: 1 }, price: 420, description: 'Позднеигровой аварийный комплект.' },
  { id: 'scarlet_potion', label: 'Scarlet Potion', key: 'scarletPotion', price: 150, amount: 1, description: 'Сильное лечение одного союзника.' },
  { id: 'purifying_herb', label: 'Purifying Herb', key: 'purifyingHerb', price: 35, amount: 1, description: 'Снятие яда и лёгкое лечение.' },
  { id: 'poff_nut', label: 'Poff Nut', key: 'poffNut', price: 25, amount: 1, description: 'Небольшое лечение.' },
  { id: 'seed_of_life', label: 'Seed of Life', key: 'seedOfLife', price: 75, amount: 1, description: 'Заметное лечение.' },
  { id: 'seed_of_psyche', label: 'Seed of Psyche', key: 'seedOfPsyche', price: 60, amount: 1, description: 'Восстановление SP.' },
  { id: 'seed_of_magic', label: 'Seed of Magic', key: 'seedOfMagic', price: 75, amount: 1, description: 'Восстановление MP.' },
  { id: 'mana_crystal', label: 'Mana Crystal', key: 'manaCrystal', price: 120, amount: 1, description: 'Много MP одному союзнику.' },
  { id: 'caterpillar_soup', label: 'Caterpillar Soup', key: 'caterpillarSoup', price: 95, amount: 1, description: 'Массовое лечение и снятие яда.' },
  { id: 'paralysis_salve', label: 'Paralysis Salve', key: 'paralysisSalve', price: 50, amount: 1, description: 'Снимает move-block.' },
  { id: 'firebomb', label: 'Firebomb', key: 'firebomb', price: 80, amount: 1, description: 'Огненный урон по одной цели.' },
  { id: 'mogay_bomb', label: 'Mogay Bomb', key: 'mogayBomb', price: 110, amount: 1, description: 'Огненный урон по всем врагам.' },
  { id: 'hand_grenade', label: 'Hand Grenade', key: 'handGrenade', price: 130, amount: 1, description: 'Урон по всем врагам.' },
  { id: 'meteor_scroll', label: 'Meteor Scroll', key: 'meteorScroll', price: 320, amount: 1, description: 'Сильный огненный урон по всем врагам.' },
  { id: 'whirlwind_scroll', label: 'Whirlwind Scroll', key: 'whirlwindScroll', price: 240, amount: 1, description: 'Ветровой урон по всем врагам.' },
  { id: 'scroll_of_alheal', label: 'Scroll of Alheal', key: 'scrollOfAlheal', price: 180, amount: 1, description: 'Массовое лечение группы.' },
  { id: 'field_pack_plus', label: 'Field Pack+', bundle: { poffNut: 2, purifyingHerb: 1, firebomb: 1 }, price: 140, description: 'Походный набор с боеприпасами.' },
  { id: 'seed_pack', label: 'Seed Pack', bundle: { seedOfLife: 1, seedOfPsyche: 1, seedOfMagic: 1 }, price: 200, description: 'Набор семян для тяжёлых стычек.' },
  { id: 'bomb_pack', label: 'Bomb Pack', bundle: { mogayBomb: 2, handGrenade: 1 }, price: 320, description: 'Поздний набор взрывчатки.' },
  { id: 'scroll_pack', label: 'Scroll Pack', bundle: { whirlwindScroll: 1, scrollOfAlheal: 1 }, price: 400, description: 'Редкие свитки для финальных областей.' },
  { id: 'sympathy_nut', label: 'Sympathy Nut', key: 'sympathyNut', price: 45, amount: 1, description: 'Заметное лечение одного союзника.' },
  { id: 'seed_of_running', label: 'Seed of Running', key: 'seedOfRunning', price: 40, amount: 1, description: 'Немного SP.' },

  { id: 'healing_fruit', label: 'Healing Fruit', key: 'healingFruit', price: 120, amount: 1, description: 'Заметное лечение одного союзника.' },
  { id: 'potion_of_azure', label: 'Potion of Azure', key: 'potionOfAzure', price: 300, amount: 1, description: 'Сильное лечение всей группы.' },
  { id: 'tortes_reedpipe', label: 'Torte\'s Reedpipe', key: 'tortesReedpipe', price: 30, amount: 1, description: 'Снимает сон.' },
  { id: 'smelling_salts', label: 'Smelling Salts', key: 'smellingSalts', price: 20, amount: 1, description: 'Снимает сон и паралич.' },
  { id: 'blessing_scroll', label: 'Blessing Scroll', key: 'blessingScroll', price: 150, amount: 1, description: 'Снимает все статусы.' },
  { id: 'vaccine', label: 'Vaccine', key: 'vaccine', price: 100, amount: 1, description: 'Снимает яд.' },
  { id: 'holy_ashes', label: 'Holy Ashes', key: 'holyAshes', price: 400, amount: 1, description: 'Воскрешает павшего союзника.' },
  { id: 'myriad_power_nut', label: 'Myriad Power Nut', key: 'myriadPowerNut', price: 20, amount: 1, description: 'Восстанавливает SP.' },
  { id: 'patience_nut', label: 'Patience Nut', key: 'patienceNut', price: 20, amount: 1, description: 'Небольшое лечение.' },
  { id: 'swiftness_nut', label: 'Swiftness Nut', key: 'swiftnessNut', price: 20, amount: 1, description: 'Восстанавливает SP.' },
  { id: 'slowpoke_nut', label: 'Slowpoke Nut', key: 'slowpokeNut', price: 20, amount: 1, description: 'Крошечное лечение.' },
  { id: 'dynamite', label: 'Dynamite', key: 'dynamite', price: 150, amount: 1, description: 'Огненный урон по всем врагам.' },
  { id: 'hyper_mogay_bomb', label: 'Hyper Mogay Bomb', key: 'hyperMogayBomb', price: 300, amount: 1, description: 'Сильный огненный урон по всем.' },
  { id: 'super_mogay_bomb', label: 'Super Mogay Bomb', key: 'superMogayBomb', price: 450, amount: 1, description: 'Мощнейший огненный урон по всем.' },
  { id: 'magical_medicine', label: 'Magical Medicine', key: 'magicalMedicine', price: 250, amount: 1, description: 'Сильное лечение всей группы.' },
  { id: 'golden_potion', label: 'Golden Potion', key: 'goldenPotion', price: 400, amount: 1, description: 'Очень сильное лечение всей группы.' },
  { id: 'hero_elixir', label: 'Hero\'s Elixir', key: 'heroElixir', price: 500, amount: 1, description: 'Полное лечение и снятие статусов.' },
];

export const SHOP_STOCK_BY_LOCATION = {
  carbo_store: ['herb', 'antidote', 'eye_drops', 'poff_nut', 'field_pack'],
  agear_guard_tent: ['herb', 'antidote', 'wound_salve', 'move_blessing', 'purifying_herb', 'firebomb', 'field_pack'],
  liligue_store: ['herb', 'antidote', 'wound_salve', 'blueberry', 'lumir_flower', 'seed_of_life', 'restoration_pack'],
  mirumu_store: ['herb', 'antidote', 'eye_drops', 'magic_blessing', 'lumir_flower', 'paralysis_salve', 'field_pack'],
  cyrum_store: ['herb', 'wound_salve', 'healing_herb', 'blueberry', 'lumir_flower', 'magic_blessing', 'panacea', 'healing_incense', 'mana_crystal', 'seed_pack', 'restoration_pack'],
  st_heim_store: ['herb', 'antidote', 'wound_salve', 'healing_herb', 'eye_drops', 'move_blessing', 'magic_blessing', 'panacea', 'scarlet_potion', 'restoration_pack'],
  cyrum_store: ['herb', 'wound_salve', 'healing_herb', 'blueberry', 'lumir_flower', 'magic_blessing', 'panacea', 'healing_incense', 'mana_crystal', 'seed_pack', 'restoration_pack'],
  garlan_store: ['wound_salve', 'healing_herb', 'eye_drops', 'move_blessing', 'blueberry', 'seed_of_psyche', 'field_pack', 'restoration_pack'],
  nanan_store: ['wound_salve', 'healing_herb', 'move_blessing', 'magic_blessing', 'panacea', 'yomis_elixir', 'blueberry', 'lumir_flower', 'healing_incense', 'scarlet_potion', 'caterpillar_soup', 'bomb_pack', 'scroll_pack', 'rescue_pack'],
};

export function getShopEntriesForLocation(locationId) {
  const ids = SHOP_STOCK_BY_LOCATION[locationId] ?? [];
  return ids
    .map((shopId) => SHOP_CATALOG.find((entry) => entry.id === shopId) ?? null)
    .filter(Boolean);
}

export const EQUIPMENT_CATALOG = [
  { id: 'ryudo-hunter-blade', label: 'Hunter Blade', slot: 'weapon', targetKey: 'ryudo', price: 140, bonuses: { str: 4 }, description: 'Меч для Рюдо: повышает физический урон.' },
  { id: 'ryudo-viper-blade', label: 'Viper Blade', slot: 'weapon', targetKey: 'ryudo', price: 220, bonuses: { str: 5, agi: 1 }, description: 'Более быстрый геохаунд-меч под cancel play.' },
  { id: 'ryudo-granas-edge', label: 'Granas Edge', slot: 'weapon', targetKey: 'ryudo', price: 340, bonuses: { str: 7, spd: 1 }, description: 'Поздний меч для усиления тяжёлых special moves.' },
  { id: 'ryudo-geohound-mail', label: 'Geohound Mail', slot: 'armor', targetKey: 'ryudo', price: 160, bonuses: { maxHp: 28, vit: 2 }, description: 'Защитная броня геохаунда.' },
  { id: 'ryudo-rift-mail', label: 'Rift Mail', slot: 'armor', targetKey: 'ryudo', price: 280, bonuses: { maxHp: 42, vit: 3, men: 1 }, description: 'Тяжёлая броня для поздних сюжетных прорывов.' },
  { id: 'ryudo-pirates-ring', label: "Pirate's Ring", slot: 'accessory', targetKey: 'ryudo', price: 260, bonuses: { agi: 2, spd: 2 }, description: 'Ускоряет темп хода и ближе к оригинальной ролевой подаче Ryudo.' },

  { id: 'elena-songstaff', label: 'Song Staff', slot: 'weapon', targetKey: 'elena', price: 150, bonuses: { mag: 4, men: 2 }, description: 'Посох певчей для магии и поддержки.' },
  { id: 'elena-holy-mace', label: 'Holy Mace', slot: 'weapon', targetKey: 'elena', price: 260, bonuses: { mag: 5, men: 3 }, description: 'Позднее церковное оружие под heal/support build.' },
  { id: 'elena-vestment', label: 'Sister Vestment', slot: 'armor', targetKey: 'elena', price: 140, bonuses: { maxMp: 8, men: 2 }, description: 'Церковное облачение, помогающее выживаемости и магии.' },
  { id: 'elena-papal-dress', label: 'Papal Dress', slot: 'armor', targetKey: 'elena', price: 290, bonuses: { maxHp: 18, maxMp: 12, men: 3 }, description: 'Тяжёлое позднее облачение святого города.' },
  { id: 'elena-prayer-bangle', label: 'Prayer Bangle', slot: 'accessory', targetKey: 'elena', price: 250, bonuses: { mag: 2, men: 3, maxMp: 6 }, description: 'Усиливает role Elena как главного саппорта.' },

  { id: 'roan-court-saber', label: 'Court Saber', slot: 'weapon', targetKey: 'roan', price: 150, bonuses: { str: 2, mag: 3 }, description: 'Оружие молодого принца: немного силы и тактики.' },
  { id: 'roan-ceremonial-sword', label: 'Ceremonial Sword', slot: 'weapon', targetKey: 'roan', price: 250, bonuses: { str: 3, mag: 4, agi: 1 }, description: 'Более зрелое оружие для принца и utility-сборки.' },
  { id: 'roan-royal-cloak', label: 'Royal Cloak', slot: 'armor', targetKey: 'roan', price: 145, bonuses: { maxHp: 20, men: 3 }, description: 'Плащ, усиливающий выживаемость и ментальную защиту.' },
  { id: 'roan-snow-cloak', label: 'Snow Cloak', slot: 'armor', targetKey: 'roan', price: 270, bonuses: { maxHp: 24, men: 3, mag: 2 }, description: 'Подчёркивает магико-тактическую роль Roan.' },
  { id: 'roan-signet', label: 'Prince Signet', slot: 'accessory', targetKey: 'roan', price: 260, bonuses: { agi: 2, men: 2, maxMp: 4 }, description: 'Поздняя королевская регалия под command-support стиль.' },

  { id: 'mareg-horn-bracer', label: 'Horn Bracer', slot: 'weapon', targetKey: 'mareg', price: 160, bonuses: { str: 5 }, description: 'Усиление грубой силы Марега.' },
  { id: 'mareg-earth-fang', label: 'Earth Fang', slot: 'weapon', targetKey: 'mareg', price: 285, bonuses: { str: 7, vit: 1 }, description: 'Поздний клыкастый усилитель тяжёлых звериных ударов.' },
  { id: 'mareg-warhide', label: 'Warhide Harness', slot: 'armor', targetKey: 'mareg', price: 170, bonuses: { maxHp: 36, vit: 3 }, description: 'Тяжёлая сбруя для фронтовика.' },
  { id: 'mareg-clan-hide', label: 'Clan Hide', slot: 'armor', targetKey: 'mareg', price: 300, bonuses: { maxHp: 50, vit: 4, men: 1 }, description: 'Клановая late-game броня для живой стены партии.' },
  { id: 'mareg-beast-charm', label: 'Beast Charm', slot: 'accessory', targetKey: 'mareg', price: 260, bonuses: { str: 2, maxHp: 18 }, description: 'Поддерживает роль Mareg как тяжёлого бруизера.' },

  { id: 'tio-aegis-frame', label: 'Aegis Frame', slot: 'weapon', targetKey: 'tio', price: 165, bonuses: { agi: 2, mag: 4 }, description: 'Корпусной апгрейд Тио под скорость и магию.' },
  { id: 'tio-whisper-core', label: 'Whisper Core', slot: 'weapon', targetKey: 'tio', price: 280, bonuses: { mag: 5, spd: 2 }, description: 'Поздний апгрейд под поддержку и звёздный utility-play.' },
  { id: 'tio-signal-boots', label: 'Signal Boots', slot: 'armor', targetKey: 'tio', price: 140, bonuses: { spd: 3, maxMp: 6 }, description: 'Лёгкий апгрейд для мобильной поддержки.' },
  { id: 'tio-logic-shell', label: 'Logic Shell', slot: 'armor', targetKey: 'tio', price: 275, bonuses: { maxHp: 18, maxMp: 10, men: 2 }, description: 'Укрепляет поздний support/control профиль Тио.' },
  { id: 'tio-star-module', label: 'Star Module', slot: 'accessory', targetKey: 'tio', price: 265, bonuses: { mag: 3, agi: 2, spd: 1 }, description: 'Аксессуар под faster action economy.' },

  { id: 'millenia-witch-ribbon', label: 'Witch Ribbon', slot: 'accessory', targetKey: 'millenia', price: 150, bonuses: { mag: 4, agi: 2 }, description: 'Усиливает колдовскую мощь Миллении.' },
  { id: 'millenia-feather-coat', label: 'Feather Coat', slot: 'armor', targetKey: 'millenia', price: 160, bonuses: { maxHp: 18, men: 2, maxMp: 6 }, description: 'Защита и магическая устойчивость.' },
  { id: 'millenia-chaos-heels', label: 'Chaos Heels', slot: 'weapon', targetKey: 'millenia', price: 275, bonuses: { str: 2, mag: 5, agi: 1 }, description: 'Позднее offensive-оружие Миллении.' },
  { id: 'millenia-valmar-silk', label: 'Valmar Silk', slot: 'armor', targetKey: 'millenia', price: 320, bonuses: { maxHp: 20, maxMp: 12, mag: 2 }, description: 'Лейтгейм-броня для burst caster build.' },
  { id: 'millenia-moon-brooch', label: 'Moon Brooch', slot: 'accessory', targetKey: 'millenia', price: 295, bonuses: { mag: 4, maxMp: 8 }, description: 'Поднимает burst-магический потолок Миллении.' },

  { id: 'party-field-rations', label: 'Field Rations', slot: 'consumable-pack', price: 120, bonuses: { medicinalHerb: 2, antidote: 2, eyeDrops: 1 }, description: 'Полевой набор для всей партии.' },
  { id: 'party-late-rations', label: 'Late War Rations', slot: 'consumable-pack', price: 260, bonuses: { woundSalve: 2, blueberry: 1, lumirFlower: 1 }, description: 'Сильный походный набор под поздние битвы.' },
  { id: 'party-bomb-rations', label: 'Bomb Rations', slot: 'consumable-pack', price: 220, bonuses: { poffNut: 2, firebomb: 2, purifyingHerb: 1 }, description: 'Набор с боевыми расходниками.' },
  { id: 'party-seed-rations', label: 'Seed Rations', slot: 'consumable-pack', price: 300, bonuses: { seedOfLife: 1, seedOfPsyche: 1, seedOfMagic: 1, scrollOfAlheal: 1 }, description: 'Поздний набор из семян и свитков.' },

  { id: 'ryudo-falx', label: 'Falx', slot: 'weapon', targetKey: 'ryudo', price: 500, bonuses: { str: 5, spd: 1 }, description: 'Серповидный меч геохаунда.' },
  { id: 'ryudo-shamshir', label: 'Shamshir', slot: 'weapon', targetKey: 'ryudo', price: 620, bonuses: { str: 6, agi: 1 }, description: 'Изогнутый клинок с хвостом льва.' },
  { id: 'ryudo-army-saber', label: 'Army Saber', slot: 'weapon', targetKey: 'ryudo', price: 750, bonuses: { str: 8 }, description: 'Армейская сабля.' },
  { id: 'ryudo-samurai-blade', label: 'Samurai Blade', slot: 'weapon', targetKey: 'ryudo', price: 900, bonuses: { str: 10, spd: 1 }, description: 'Самурайский клинок.' },
  { id: 'ryudo-claymore', label: 'Claymore', slot: 'weapon', targetKey: 'ryudo', price: 3600, bonuses: { str: 15, vit: 1 }, description: 'Огромный двуручный меч.' },
  { id: 'ryudo-fine-broadsword', label: 'Fine Broadsword', slot: 'weapon', targetKey: 'ryudo', price: 4500, bonuses: { str: 18, agi: 1 }, description: 'Меч, выкованный мастером.' },
  { id: 'ryudo-sword-of-purity', label: 'Sword of Purity', slot: 'weapon', targetKey: 'ryudo', price: 0, bonuses: { str: 10, men: 2 }, description: 'Меч, эффективный против нежити. Дроп: Gargoyle.' },
  { id: 'ryudo-ogre-slayer', label: 'Ogre Slayer', slot: 'weapon', targetKey: 'ryudo', price: 0, bonuses: { str: 14 }, description: 'Эффективен против гуманоидов. Дроп: Hell Hound.' },
  { id: 'ryudo-maken-valborg', label: 'Maken Valborg', slot: 'weapon', targetKey: 'ryudo', price: 0, bonuses: { str: 24, maxHp: 20 }, description: 'Меч, поглощающий 10% урона как HP. Дроп: Melfice.' },

  { id: 'elena-quilted-silk', label: 'Quilted Silk', slot: 'armor', targetKey: 'elena', price: 800, bonuses: { maxMp: 10, men: 2 }, description: 'Магическое шёлковое облачение.' },
  { id: 'elena-guardian-robe', label: 'Guardian Robe', slot: 'armor', targetKey: 'elena', price: 1200, bonuses: { maxHp: 20, men: 3, maxMp: 6 }, description: 'Роба стража с сопротивлением яду.' },
  { id: 'elena-pixie-robe', label: "Pixie's Robe", slot: 'armor', targetKey: 'elena', price: 2600, bonuses: { maxMp: 14, men: 4 }, description: 'Роба пикси: устойчивость ко сну.' },
  { id: 'elena-dragon-wand', label: 'Dragon Wand', slot: 'weapon', targetKey: 'elena', price: 0, bonuses: { mag: 8, men: 3 }, description: 'Драконий жезл. Дроп: Dragon Knight.' },
  { id: 'elena-friends-necklace', label: 'Friends Necklace', slot: 'accessory', targetKey: 'elena', price: 0, bonuses: { maxHp: 16, men: 2 }, description: 'Символ искренней дружбы.' },

  { id: 'roan-chain-mail', label: 'Chain Mail', slot: 'armor', targetKey: 'roan', price: 950, bonuses: { maxHp: 24, vit: 2 }, description: 'Кольчужная рубаха.' },
  { id: 'roan-silver-bracelet', label: 'Silver Bracelet', slot: 'accessory', targetKey: 'roan', price: 0, bonuses: { maxHp: 12, men: 1 }, description: 'Серебряный браслет.' },
  { id: 'roan-shogun-brace', label: "Shogun's Brace", slot: 'accessory', targetKey: 'roan', price: 5000, bonuses: { maxHp: 30, vit: 2, agi: 1 }, description: 'Браслет сёгуна: поздний защитный аксессуар.' },

  { id: 'mareg-plate-mail', label: 'Plate Mail', slot: 'armor', targetKey: 'mareg', price: 1400, bonuses: { maxHp: 40, vit: 3 }, description: 'Цельнометаллическая броня.' },
  { id: 'mareg-swordfish-armor', label: 'Swordfish Armor', slot: 'armor', targetKey: 'mareg', price: 2800, bonuses: { maxHp: 48, vit: 4 }, description: 'Броня из чешуи рыбы-меча.' },
  { id: 'mareg-rage-ring', label: 'Rage Ring', slot: 'accessory', targetKey: 'mareg', price: 0, bonuses: { str: 3 }, description: 'Кольцо ярости: урон повышает SP recovery.' },
  { id: 'mareg-black-belt', label: 'Black Belt', slot: 'accessory', targetKey: 'mareg', price: 0, bonuses: { str: 4, agi: 1 }, description: 'Чёрный пояс: усиливает special moves.' },

  { id: 'tio-ancient-suit', label: 'Ancient Suit', slot: 'armor', targetKey: 'tio', price: 0, bonuses: { maxHp: 24, maxMp: 12, men: 3 }, description: 'Броня древних автоматонов.' },
  { id: 'tio-magical-brace', label: 'Magical Brace', slot: 'accessory', targetKey: 'tio', price: 1500, bonuses: { mag: 3, maxMp: 8 }, description: 'Магический браслет.' },
  { id: 'tio-platinum-feather', label: 'Platinum Feather', slot: 'accessory', targetKey: 'tio', price: 0, bonuses: { spd: 3, agi: 2 }, description: 'Платиновое перо: ускоряет темп. Дроп: Valmar Fly.' },

  { id: 'millenia-crimson-bolero', label: 'Crimson Bolero', slot: 'armor', targetKey: 'millenia', price: 0, bonuses: { maxHp: 18, maxMp: 10, mag: 2 }, description: 'Страстная красная куртка.' },
  { id: 'millenia-flare-dress', label: 'Flare Dress', slot: 'armor', targetKey: 'millenia', price: 0, bonuses: { maxMp: 14, mag: 3 }, description: 'Платье с сопротивлением огню.' },
  { id: 'millenia-salamander-tail', label: 'Salamander Tail', slot: 'accessory', targetKey: 'millenia', price: 0, bonuses: { mag: 4, fireResist: 1 }, description: 'Хвост саламандры. Дроп: Salamadile.' },
  { id: 'millenia-tight-dress', label: 'Tight Dress', slot: 'armor', targetKey: 'millenia', price: 0, bonuses: { maxHp: 22, mag: 4, maxMp: 8 }, description: 'Позднее платье с лунной символикой. Дроп: Nyarmot.' },
  { id: 'millenia-thor-stone', label: 'Thor Stone', slot: 'accessory', targetKey: 'millenia', price: 0, bonuses: { mag: 5, maxMp: 10 }, description: 'Камень Тора: всплеск магической силы.' },
  { id: 'elena-pretty-ring', label: 'Pretty Ring', slot: 'accessory', targetKey: 'elena', price: 0, bonuses: { maxMp: 8, men: 2 }, description: 'Красивое кольцо с зеркальным блеском.' },
  { id: 'roan-reflection-ring', label: 'Reflection Ring', slot: 'accessory', targetKey: 'roan', price: 0, bonuses: { men: 3, maxMp: 6 }, description: 'Кольцо отражения из глубин Лилига.' },
  { id: 'party-sleep-charm', label: 'Sleep Charm', slot: 'accessory', targetKey: null, price: 250, bonuses: { resistSleep: 0.5, men: 1 }, description: 'Амулет сна: устойчивость к sleep.' },
  { id: 'party-poison-charm', label: 'Poison Charm', slot: 'accessory', targetKey: null, price: 250, bonuses: { resistPoison: 0.5, men: 1 }, description: 'Амулет яда: устойчивость к poison.' },
  { id: 'party-confusion-charm', label: 'Confusion Charm', slot: 'accessory', targetKey: null, price: 250, bonuses: { resistConfusion: 0.5, men: 1 }, description: 'Амулет смятения: устойчивость к confusion.' },
  { id: 'party-paralysis-charm', label: 'Paralysis Charm', slot: 'accessory', targetKey: null, price: 250, bonuses: { resistParalysis: 0.5, men: 1 }, description: 'Амулет паралича: устойчивость к paralysis.' },
  { id: 'party-moveblock-charm', label: 'Move Block Charm', slot: 'accessory', targetKey: null, price: 400, bonuses: { resistMoveBlock: 0.5, vit: 1 }, description: 'Амулет блока движения: устойчивость к move-block.' },
  { id: 'party-magicblock-charm', label: 'Magic Block Charm', slot: 'accessory', targetKey: null, price: 400, bonuses: { resistMagicBlock: 0.5, men: 2 }, description: 'Амулет блока магии: устойчивость к magic-block.' },
  { id: 'party-healing-ring', label: 'Healing Ring', slot: 'accessory', targetKey: null, price: 500, bonuses: { maxHp: 24, men: 2 }, description: 'Кольцо исцеления: постоянная регенерация духа.' },
  { id: 'party-relief-tag', label: 'Relief Tag', slot: 'accessory', targetKey: null, price: 4000, bonuses: { resistPoison: 0.7, resistSleep: 0.7, men: 3 }, description: 'Билет облегчения: сильная устойчивость к яду и сну.' },

  { id: 'ryudo-flamberge', label: 'Flamberge', slot: 'weapon', targetKey: 'ryudo', price: 0, bonuses: { str: 11, agi: 1 }, description: 'Огненный меч из глубин Лилига (Burn!).' },
  { id: 'ryudo-silver-freeze', label: 'Silver Freeze', slot: 'weapon', targetKey: 'ryudo', price: 0, bonuses: { str: 20, spd: 1 }, description: 'Серебряный клинок с заморозкой. Приз Хембла.' },
  { id: 'ryudo-holy-soul-blade', label: 'Holy Soul Blade', slot: 'weapon', targetKey: 'ryudo', price: 14000, bonuses: { str: 28, men: 3 }, description: 'Святой клинок, снижающий DEF врага.' },
  { id: 'ryudo-blazing-sword', label: 'Blazing Sword', slot: 'weapon', targetKey: 'ryudo', price: 17000, bonuses: { str: 30, agi: 2 }, description: 'Пылающий меч позднего Цайрума.' },
  { id: 'ryudo-icefang-sword', label: 'Icefang Sword', slot: 'weapon', targetKey: 'ryudo', price: 18000, bonuses: { str: 31, spd: 2 }, description: 'Ледяной клык: ледяной урон.' },
  { id: 'ryudo-thor-sword', label: 'Thor Sword', slot: 'weapon', targetKey: 'ryudo', price: 19000, bonuses: { str: 32, agi: 3 }, description: 'Громовой меч: молниевый урон.' },
  { id: 'ryudo-granasaber', label: 'Granasaber', slot: 'weapon', targetKey: 'ryudo', price: 0, bonuses: { str: 38, agi: 2, spd: 2 }, description: 'Легендарный меч Граноса: снижает трату SP.' },
  { id: 'tio-moon-claw', label: 'Moon Claw', slot: 'weapon', targetKey: 'tio', price: 1500, bonuses: { mag: 5, agi: 2 }, description: 'Когтевой клинок с лунным серпом.' },
  { id: 'tio-double-moon', label: 'Double Moon', slot: 'weapon', targetKey: 'tio', price: 2600, bonuses: { mag: 6, agi: 3 }, description: 'Два боевых диска-полумесяца.' },
  { id: 'tio-discus', label: 'Discus', slot: 'weapon', targetKey: 'tio', price: 3400, bonuses: { mag: 7, spd: 2 }, description: 'Метательный диск, эффективный против насекомых.' },
  { id: 'tio-binding-circle', label: 'Binding Circle', slot: 'weapon', targetKey: 'tio', price: 0, bonuses: { mag: 8, agi: 2 }, description: 'Круг паралича: шанс парализовать цель.' },
  { id: 'tio-balor', label: 'Balor', slot: 'weapon', targetKey: 'tio', price: 6200, bonuses: { mag: 9, men: 2 }, description: 'Оружие с уменьшенной тратой SP.' },
  { id: 'tio-angel-circle', label: 'Angel Circle', slot: 'weapon', targetKey: 'tio', price: 0, bonuses: { mag: 10, men: 2 }, description: 'Эффективно против нежити.' },
  { id: 'tio-demon-shuriken', label: 'Demon Shuriken', slot: 'weapon', targetKey: 'tio', price: 9000, bonuses: { mag: 11, agi: 4 }, description: 'Демонический сюрикен: +ACT.' },
  { id: 'roan-hunters-knife', label: 'Hunter\'s Knife', slot: 'weapon', targetKey: 'roan', price: 880, bonuses: { str: 5, agi: 2 }, description: 'Охотничий нож, эффективный против зверей.' },
  { id: 'roan-flint-knife', label: 'Flint Knife', slot: 'weapon', targetKey: 'roan', price: 2000, bonuses: { str: 9, agi: 3 }, description: 'Обсидиановый нож.' },
  { id: 'roan-ice-pick', label: 'Ice Pick', slot: 'weapon', targetKey: 'roan', price: 0, bonuses: { str: 7, mag: 3 }, description: 'Ледяная кирка: морозный урон.' },
  { id: 'roan-warp-knife', label: 'Warp Knife', slot: 'weapon', targetKey: 'roan', price: 4200, bonuses: { str: 10, agi: 4 }, description: 'Нож, телепортирующий во время боя.' },
  { id: 'roan-multiple-knife', label: 'Multiple Knife', slot: 'weapon', targetKey: 'roan', price: 0, bonuses: { str: 6, mag: 2 }, description: 'Многофункциональный нож.' },
  { id: 'millenia-crossbow', label: 'Crossbow', slot: 'weapon', targetKey: 'millenia', price: 0, bonuses: { mag: 7, agi: 2 }, description: 'Мощный арбалет Миллении.' },
  { id: 'millenia-flying-fish-bow', label: 'Flying Fish Bow', slot: 'weapon', targetKey: 'millenia', price: 0, bonuses: { mag: 9, agi: 3 }, description: 'Лук, хороший против птиц.' },
  { id: 'mareg-tundra-battleax', label: 'Tundra Battleax', slot: 'weapon', targetKey: 'mareg', price: 0, bonuses: { str: 20, vit: 2 }, description: 'Ледяной боевой топор.' },
  { id: 'ancient-cuirass', label: 'Ancient Cuirass', slot: 'armor', targetKey: 'ryudo', price: 0, bonuses: { maxHp: 60, vit: 4 }, description: 'Древний нагрудник: снижает замедление IP.' },
  { id: 'halo-armor', label: 'Halo Armor', slot: 'armor', targetKey: 'ryudo', price: 7600, bonuses: { maxHp: 64, vit: 4, men: 2 }, description: 'Броня ореола: сопротивление молнии.' },
  { id: 'moonstone-armor', label: 'Moonstone Armor', slot: 'armor', targetKey: 'ryudo', price: 9000, bonuses: { maxHp: 72, vit: 5 }, description: 'Лунный камень: сопротивление magic-block.' },
  { id: 'holy-clothes', label: 'Holy Clothes', slot: 'armor', targetKey: 'ryudo', price: 0, bonuses: { maxHp: 66, vit: 4, men: 3 }, description: 'Святые одежды: устойчивость к чуме. Дроп: Valmar\'s Heart.' },
  { id: 'sun-robe', label: 'Sun Robe', slot: 'armor', targetKey: 'ryudo', price: 13750, bonuses: { maxHp: 78, vit: 5, men: 3 }, description: 'Солнечная роба: снижает замедление IP.' },
  { id: 'ninja-clothes', label: 'Ninja Clothes', slot: 'armor', targetKey: 'ryudo', price: 0, bonuses: { maxHp: 62, vit: 4, spd: 3 }, description: 'Одежда ниндзя: +уклонение.' },
  { id: 'dark-armor', label: 'Dark Armor', slot: 'armor', targetKey: 'ryudo', price: 0, bonuses: { maxHp: 60, vit: 4 }, description: 'Тёмная броня: +SP при получении урона.' },
  { id: 'valkyrie-dress', label: 'Valkyrie Dress', slot: 'armor', targetKey: 'elena', price: 0, bonuses: { maxHp: 44, maxMp: 18, mag: 4 }, description: 'Платье валькирии из Истока богов.' },
  { id: 'angel-robe', label: 'Angel\'s Robe', slot: 'armor', targetKey: 'elena', price: 0, bonuses: { maxHp: 52, maxMp: 20, men: 4 }, description: 'Роба ангела. Дроп: Egg Guardian.' },
  { id: 'hero-cuirass', label: 'Hero\'s Cuirass', slot: 'armor', targetKey: 'mareg', price: 12000, bonuses: { maxHp: 88, vit: 6 }, description: 'Нагрудник героя.' },
  { id: 'jet-black-cape', label: 'Jet Black Cape', slot: 'armor', targetKey: 'millenia', price: 0, bonuses: { maxHp: 40, maxMp: 16, mag: 4 }, description: 'Чёрный плащ с сопротивлением тьме.' },
  { id: 'reflect-mail', label: 'Reflect Mail', slot: 'armor', targetKey: 'roan', price: 0, bonuses: { maxHp: 40, men: 4, mag: 3 }, description: 'Зеркальная кольчуга: отражает слабую магию.' },
  { id: 'mirage-earring', label: 'Mirage Earring', slot: 'accessory', targetKey: 'tio', price: 0, bonuses: { spd: 3, agi: 2 }, description: 'Серьга мираж: +уклонение.' },
  { id: 'silver-feather', label: 'Silver Feather', slot: 'accessory', targetKey: 'ryudo', price: 0, bonuses: { spd: 3 }, description: 'Серебряное перо: ускоряет темп.' },
  { id: 'gold-feather', label: 'Gold Feather', slot: 'accessory', targetKey: 'elena', price: 0, bonuses: { spd: 3, men: 2 }, description: 'Золотое перо: скорость и дух.' },
  { id: 'pretty-bracelet', label: 'Pretty Bracelet', slot: 'accessory', targetKey: 'elena', price: 0, bonuses: { men: 4, maxMp: 6 }, description: 'Красивый браслет.' },
  { id: 'red-hair-ribbon', label: 'Red Hair Ribbon', slot: 'accessory', targetKey: 'millenia', price: 0, bonuses: { agi: 3, men: 2 }, description: 'Красная лента: скорость и дух.' },
  { id: 'serpentine', label: 'Serpentine', slot: 'accessory', targetKey: 'roan', price: 0, bonuses: { men: 4, agi: 2 }, description: 'Змеиный самоцвет.' },
  { id: 'angel-ring', label: 'Angel\'s Ring', slot: 'accessory', targetKey: 'elena', price: 9000, bonuses: { maxHp: 30, men: 4 }, description: 'Кольцо ангела: защита и дух.' },
  { id: 'phoenix-ring', label: 'Phoenix Ring', slot: 'accessory', targetKey: 'mareg', price: 10000, bonuses: { maxHp: 40, vit: 2 }, description: 'Кольцо феникса: шанс возродиться однажды.' },
  { id: 'kojin-charm', label: 'Kojin Charm', slot: 'accessory', targetKey: 'mareg', price: 0, bonuses: { str: 4, vit: 2 }, description: 'Амулет Кодзин: сила и стойкость.' },
  { id: 'book-of-sages', label: 'Book of Sages', slot: 'accessory', targetKey: 'roan', price: 0, bonuses: { mag: 5, men: 3 }, description: 'Книга мудрецов: магия и дух.' },
  { id: 'dragon-bone-helm', label: 'Dragon Bone Helm', slot: 'accessory', targetKey: 'ryudo', price: 0, bonuses: { vit: 4, men: 2 }, description: 'Шлем из кости дракона.' },
  { id: 'ogre-helm', label: 'Ogre Helm', slot: 'accessory', targetKey: 'mareg', price: 0, bonuses: { vit: 4, str: 2 }, description: 'Шлем огра: стойкость и сила.' },
  { id: 'elf-king-boots', label: 'Elf King\'s Boots', slot: 'accessory', targetKey: 'tio', price: 0, bonuses: { spd: 4, agi: 2 }, description: 'Сапоги короля эльфов: скорость движения.' },
  { id: 'charming-heels', label: 'Charming Heels', slot: 'accessory', targetKey: 'millenia', price: 0, bonuses: { spd: 3, agi: 3 }, description: 'Очаровательные каблуки.' },
  { id: 'goddess-hi-heels', label: 'Goddess Hi-Heels', slot: 'accessory', targetKey: 'elena', price: 0, bonuses: { spd: 3, men: 3 }, description: 'Высокие каблуки богини.' },
  { id: 'calming-harp', label: 'Calming Harp', slot: 'accessory', targetKey: 'elena', price: 0, bonuses: { resistConfusion: 0.5, men: 2 }, description: 'Арфа спокойствия: устойчивость к смятению.' },
  { id: 'snake-earrings', label: 'Snake Earrings', slot: 'accessory', targetKey: 'ryudo', price: 0, bonuses: { resistPoison: 0.5, agi: 1 }, description: 'Змеиные серьги: устойчивость к яду.' },
  { id: 'bone-harp', label: 'Bone Harp', slot: 'accessory', targetKey: 'roan', price: 0, bonuses: { men: 3, maxMp: 6 }, description: 'Арфа из кости: дух и мана.' },
];

export const EQUIPMENT_STOCK_BY_LOCATION = {
  carbo_store: ['ryudo-hunter-blade', 'elena-songstaff', 'ryudo-falx', 'party-field-rations'],
  agear_guard_tent: ['ryudo-geohound-mail', 'ryudo-shamshir', 'ryudo-army-saber', 'party-bomb-rations', 'ryudo-viper-blade', 'roan-hunters-knife'],
  liligue_store: ['elena-vestment', 'mareg-horn-bracer', 'elena-prayer-bangle', 'elena-quilted-silk', 'roan-chain-mail', 'party-field-rations'],
  mirumu_store: ['roan-court-saber', 'roan-royal-cloak', 'roan-signet', 'elena-guardian-robe', 'roan-flint-knife', 'tio-moon-claw', 'party-sleep-charm', 'party-poison-charm', 'party-field-rations'],
  st_heim_store: ['elena-holy-mace', 'elena-papal-dress', 'roan-ceremonial-sword', 'roan-snow-cloak', 'tio-signal-boots', 'ryudo-claymore', 'roan-shogun-brace', 'tio-discus', 'ryudo-holy-soul-blade', 'halo-armor', 'angel-ring', 'party-sleep-charm', 'party-poison-charm', 'party-confusion-charm', 'party-paralysis-charm', 'party-moveblock-charm', 'party-magicblock-charm', 'party-late-rations'],
  cyrum_store: ['tio-aegis-frame', 'tio-whisper-core', 'tio-logic-shell', 'tio-star-module', 'mareg-warhide', 'mareg-beast-charm', 'mareg-plate-mail', 'tio-magical-brace', 'tio-double-moon', 'tio-balor', 'tio-demon-shuriken', 'ryudo-blazing-sword', 'ryudo-icefang-sword', 'ryudo-thor-sword', 'moonstone-armor', 'phoenix-ring', 'party-healing-ring', 'party-late-rations'],
  garlan_store: ['ryudo-rift-mail', 'ryudo-pirates-ring', 'mareg-earth-fang', 'mareg-clan-hide', 'ryudo-samurai-blade', 'ryudo-fine-broadsword', 'mareg-swordfish-armor', 'roan-warp-knife', 'hero-cuirass', 'party-seed-rations', 'party-late-rations'],
  nanan_store: ['millenia-chaos-heels', 'millenia-feather-coat', 'millenia-valmar-silk', 'millenia-moon-brooch', 'elena-pixie-robe', 'sun-robe', 'party-relief-tag', 'party-late-rations'],
};

export const LOCATION_SCENE_LAYOUTS = {
  carbo_village: {
    buildingSlots: [
      { x: 84, y: 200, w: 148, h: 84 },
      { x: 262, y: 164, w: 176, h: 118 },
      { x: 486, y: 184, w: 160, h: 98 },
      { x: 688, y: 196, w: 142, h: 88 },
      { x: 210, y: 304, w: 144, h: 74 },
      { x: 448, y: 308, w: 150, h: 70 },
    ],
    gateSlots: [
      { x: 84, y: 444, w: 154, h: 40 },
      { x: 280, y: 444, w: 154, h: 40 },
      { x: 476, y: 444, w: 154, h: 40 },
      { x: 672, y: 444, w: 154, h: 40 },
    ],
    npcSlots: [{ x: 318, y: 396 }, { x: 570, y: 384 }, { x: 748, y: 358 }],
  },
  liligue_city: {
    buildingSlots: [
      { x: 92, y: 204, w: 136, h: 78 },
      { x: 252, y: 188, w: 152, h: 96 },
      { x: 430, y: 158, w: 200, h: 126 },
      { x: 688, y: 190, w: 160, h: 92 },
      { x: 176, y: 314, w: 152, h: 68 },
      { x: 526, y: 310, w: 178, h: 72 },
    ],
    gateSlots: [
      { x: 126, y: 442, w: 164, h: 40 },
      { x: 356, y: 442, w: 164, h: 40 },
      { x: 586, y: 442, w: 164, h: 40 },
    ],
    npcSlots: [{ x: 382, y: 380 }, { x: 616, y: 360 }, { x: 808, y: 392 }],
  },
  mirumu_village: {
    buildingSlots: [
      { x: 84, y: 200, w: 146, h: 82 },
      { x: 256, y: 222, w: 134, h: 60 },
      { x: 424, y: 174, w: 172, h: 108 },
      { x: 670, y: 194, w: 156, h: 88 },
      { x: 176, y: 310, w: 156, h: 72 },
      { x: 444, y: 314, w: 176, h: 70 },
    ],
    gateSlots: [
      { x: 116, y: 444, w: 176, h: 40 },
      { x: 372, y: 444, w: 176, h: 40 },
      { x: 628, y: 444, w: 176, h: 40 },
    ],
    npcSlots: [{ x: 266, y: 396 }, { x: 532, y: 362 }, { x: 766, y: 392 }],
  },
  st_heim_papal_state: {
    buildingSlots: [
      { x: 98, y: 214, w: 136, h: 68 },
      { x: 258, y: 194, w: 142, h: 88 },
      { x: 434, y: 146, w: 196, h: 138 },
      { x: 678, y: 198, w: 164, h: 84 },
      { x: 158, y: 318, w: 164, h: 68 },
      { x: 530, y: 320, w: 180, h: 68 },
    ],
    gateSlots: [
      { x: 138, y: 444, w: 182, h: 40 },
      { x: 412, y: 444, w: 182, h: 40 },
      { x: 686, y: 444, w: 182, h: 40 },
    ],
    npcSlots: [{ x: 324, y: 392 }, { x: 546, y: 372 }, { x: 768, y: 394 }],
  },
  cyrum_kingdom: {
    buildingSlots: [
      { x: 88, y: 208, w: 142, h: 74 },
      { x: 252, y: 184, w: 150, h: 98 },
      { x: 438, y: 144, w: 208, h: 138 },
      { x: 700, y: 192, w: 146, h: 88 },
      { x: 170, y: 312, w: 144, h: 72 },
      { x: 494, y: 314, w: 188, h: 70 },
    ],
    gateSlots: [
      { x: 110, y: 444, w: 176, h: 40 },
      { x: 342, y: 444, w: 176, h: 40 },
      { x: 574, y: 444, w: 176, h: 40 },
      { x: 806, y: 444, w: 120, h: 40 },
    ],
    npcSlots: [{ x: 318, y: 392 }, { x: 570, y: 362 }, { x: 802, y: 392 }],
  },
  garlan_village: {
    buildingSlots: [
      { x: 92, y: 210, w: 140, h: 72 },
      { x: 266, y: 186, w: 156, h: 96 },
      { x: 476, y: 190, w: 160, h: 92 },
      { x: 704, y: 204, w: 132, h: 78 },
      { x: 214, y: 314, w: 150, h: 68 },
      { x: 454, y: 318, w: 160, h: 66 },
    ],
    gateSlots: [
      { x: 140, y: 444, w: 186, h: 40 },
      { x: 410, y: 444, w: 186, h: 40 },
      { x: 680, y: 444, w: 186, h: 40 },
    ],
    npcSlots: [{ x: 308, y: 394 }, { x: 562, y: 372 }, { x: 760, y: 392 }],
  },
  garmia_tower: {
    walkBounds: { x: 70, y: 168, w: 860, h: 306 },
    spawn: { x: 166, y: 432 },
    routePath: [
      { x: 150, y: 418 },
      { x: 250, y: 360 },
      { x: 360, y: 312 },
      { x: 480, y: 268 },
      { x: 620, y: 224 },
      { x: 780, y: 184 },
    ],
    routeNodeSlots: [
      { x: 250, y: 360, radius: 24 },
      { x: 480, y: 268, radius: 26 },
      { x: 780, y: 184, radius: 30 },
    ],
    npcSlots: [{ x: 324, y: 226 }, { x: 646, y: 330 }],
    treasureSlots: [{ x: 214, y: 254 }, { x: 580, y: 166 }],
    encounterSlots: [{ x: 394, y: 374 }],
    obstacles: [{ x: 330, y: 180, w: 120, h: 56 }, { x: 596, y: 286, w: 140, h: 42 }],
  },
  durham_cave_entrance: {
    walkBounds: { x: 60, y: 176, w: 880, h: 300 },
    spawn: { x: 134, y: 428 },
    routePath: [
      { x: 134, y: 428 },
      { x: 230, y: 380 },
      { x: 330, y: 326 },
      { x: 470, y: 300 },
      { x: 634, y: 262 },
      { x: 786, y: 210 },
    ],
    routeNodeSlots: [
      { x: 230, y: 380, radius: 22 },
      { x: 470, y: 300, radius: 24 },
      { x: 786, y: 210, radius: 28 },
    ],
    npcSlots: [{ x: 280, y: 214 }, { x: 570, y: 378 }],
    treasureSlots: [{ x: 206, y: 226 }, { x: 702, y: 332 }],
    encounterSlots: [{ x: 520, y: 198 }],
    obstacles: [{ x: 364, y: 188, w: 110, h: 48 }, { x: 642, y: 340, w: 110, h: 40 }],
  },
  st_heim_cathedral_lobby: {
    walkBounds: { x: 82, y: 182, w: 836, h: 286 },
    spawn: { x: 500, y: 436 },
    doorSlots: [
      { x: 164, y: 218, w: 112, h: 132, targetPoint: { x: 220, y: 366 } },
      { x: 442, y: 196, w: 116, h: 156, targetPoint: { x: 500, y: 368 } },
      { x: 724, y: 218, w: 112, h: 132, targetPoint: { x: 780, y: 366 } },
      { x: 442, y: 380, w: 116, h: 72, targetPoint: { x: 500, y: 366 } },
    ],
    npcSlots: [{ x: 300, y: 312 }, { x: 700, y: 312 }],
    treasureSlots: [{ x: 500, y: 260 }],
    encounterSlots: [{ x: 500, y: 234 }],
    obstacles: [{ x: 382, y: 170, w: 236, h: 32 }],
  },
  cyrum_secret_passage: {
    walkBounds: { x: 72, y: 176, w: 850, h: 300 },
    spawn: { x: 150, y: 430 },
    routePath: [
      { x: 150, y: 430 },
      { x: 232, y: 350 },
      { x: 346, y: 290 },
      { x: 490, y: 248 },
      { x: 640, y: 220 },
      { x: 790, y: 178 },
    ],
    routeNodeSlots: [
      { x: 232, y: 350, radius: 22 },
      { x: 490, y: 248, radius: 24 },
      { x: 790, y: 178, radius: 28 },
    ],
    npcSlots: [{ x: 292, y: 228 }],
    treasureSlots: [{ x: 598, y: 342 }],
    encounterSlots: [{ x: 420, y: 380 }],
    obstacles: [{ x: 340, y: 184, w: 108, h: 40 }, { x: 646, y: 286, w: 124, h: 40 }],
  },
  underground_plant: {
    walkBounds: { x: 70, y: 170, w: 860, h: 308 },
    spawn: { x: 142, y: 428 },
    routePath: [
      { x: 142, y: 428 },
      { x: 254, y: 394 },
      { x: 378, y: 326 },
      { x: 520, y: 280 },
      { x: 680, y: 232 },
      { x: 816, y: 188 },
    ],
    routeNodeSlots: [
      { x: 254, y: 394, radius: 22 },
      { x: 520, y: 280, radius: 24 },
      { x: 816, y: 188, radius: 28 },
    ],
    npcSlots: [{ x: 310, y: 232 }, { x: 642, y: 360 }],
    treasureSlots: [{ x: 222, y: 230 }, { x: 720, y: 316 }],
    encounterSlots: [{ x: 496, y: 392 }],
    obstacles: [{ x: 368, y: 180, w: 118, h: 38 }, { x: 612, y: 274, w: 144, h: 36 }],
  },
  great_rift: {
    walkBounds: { x: 64, y: 174, w: 872, h: 304 },
    spawn: { x: 116, y: 428 },
    routePath: [
      { x: 116, y: 428 },
      { x: 224, y: 376 },
      { x: 364, y: 318 },
      { x: 506, y: 284 },
      { x: 658, y: 232 },
      { x: 812, y: 186 },
    ],
    routeNodeSlots: [
      { x: 224, y: 376, radius: 22 },
      { x: 506, y: 284, radius: 24 },
      { x: 812, y: 186, radius: 28 },
    ],
    npcSlots: [{ x: 306, y: 236 }],
    treasureSlots: [{ x: 244, y: 214 }, { x: 706, y: 338 }],
    encounterSlots: [{ x: 520, y: 392 }],
    obstacles: [{ x: 392, y: 188, w: 106, h: 44 }, { x: 624, y: 304, w: 130, h: 42 }],
  },
  demons_law: {
    walkBounds: { x: 80, y: 180, w: 840, h: 290 },
    spawn: { x: 160, y: 420 },
    routePath: [
      { x: 160, y: 420 },
      { x: 266, y: 348 },
      { x: 390, y: 292 },
      { x: 536, y: 248 },
      { x: 678, y: 216 },
      { x: 808, y: 182 },
    ],
    routeNodeSlots: [
      { x: 266, y: 348, radius: 22 },
      { x: 536, y: 248, radius: 24 },
      { x: 808, y: 182, radius: 28 },
    ],
    npcSlots: [{ x: 322, y: 228 }],
    treasureSlots: [{ x: 212, y: 218 }, { x: 724, y: 314 }],
    encounterSlots: [{ x: 484, y: 382 }],
    obstacles: [{ x: 404, y: 176, w: 120, h: 40 }, { x: 656, y: 286, w: 116, h: 34 }],
  },
  valmar_body: {
    walkBounds: { x: 68, y: 172, w: 864, h: 304 },
    spawn: { x: 126, y: 426 },
    routePath: [
      { x: 126, y: 426 },
      { x: 212, y: 356 },
      { x: 344, y: 314 },
      { x: 488, y: 272 },
      { x: 640, y: 226 },
      { x: 804, y: 192 },
    ],
    routeNodeSlots: [
      { x: 212, y: 356, radius: 22 },
      { x: 488, y: 272, radius: 24 },
      { x: 804, y: 192, radius: 30 },
    ],
    npcSlots: [{ x: 338, y: 226 }],
    treasureSlots: [{ x: 228, y: 232 }, { x: 704, y: 330 }],
    encounterSlots: [{ x: 538, y: 380 }],
    obstacles: [{ x: 396, y: 184, w: 112, h: 40 }, { x: 638, y: 312, w: 132, h: 36 }],
  },
  valmars_moon: {
    walkBounds: { x: 74, y: 176, w: 852, h: 300 },
    spawn: { x: 136, y: 430 },
    routePath: [
      { x: 136, y: 430 },
      { x: 246, y: 382 },
      { x: 378, y: 326 },
      { x: 516, y: 286 },
      { x: 666, y: 232 },
      { x: 812, y: 190 },
    ],
    routeNodeSlots: [
      { x: 246, y: 382, radius: 22 },
      { x: 516, y: 286, radius: 24 },
      { x: 812, y: 190, radius: 28 },
    ],
    npcSlots: [{ x: 322, y: 234 }, { x: 680, y: 354 }],
    treasureSlots: [{ x: 238, y: 224 }, { x: 736, y: 328 }],
    encounterSlots: [{ x: 518, y: 390 }],
    obstacles: [{ x: 390, y: 184, w: 116, h: 44 }, { x: 650, y: 300, w: 126, h: 42 }],
  },
  birthplace_of_the_gods: {
    walkBounds: { x: 72, y: 170, w: 860, h: 306 },
    spawn: { x: 128, y: 430 },
    routePath: [
      { x: 128, y: 430 },
      { x: 234, y: 368 },
      { x: 360, y: 320 },
      { x: 510, y: 278 },
      { x: 672, y: 232 },
      { x: 816, y: 188 },
    ],
    routeNodeSlots: [
      { x: 234, y: 368, radius: 22 },
      { x: 510, y: 278, radius: 24 },
      { x: 816, y: 188, radius: 28 },
    ],
    npcSlots: [{ x: 328, y: 228 }],
    treasureSlots: [{ x: 242, y: 224 }, { x: 726, y: 332 }],
    encounterSlots: [{ x: 516, y: 392 }],
    obstacles: [{ x: 386, y: 176, w: 120, h: 42 }, { x: 640, y: 304, w: 132, h: 38 }],
  },
  inner_trial: {
    walkBounds: { x: 120, y: 176, w: 760, h: 292 },
    spawn: { x: 196, y: 424 },
    routePath: [
      { x: 196, y: 424 },
      { x: 284, y: 356 },
      { x: 396, y: 300 },
      { x: 520, y: 262 },
      { x: 654, y: 214 },
    ],
    routeNodeSlots: [
      { x: 284, y: 356, radius: 22 },
      { x: 520, y: 262, radius: 24 },
      { x: 654, y: 214, radius: 28 },
    ],
    npcSlots: [{ x: 382, y: 230 }],
    treasureSlots: [{ x: 694, y: 340 }],
    encounterSlots: [{ x: 520, y: 392 }],
    obstacles: [{ x: 412, y: 174, w: 126, h: 42 }],
  },
  new_valmar: {
    walkBounds: { x: 70, y: 170, w: 860, h: 308 },
    spawn: { x: 136, y: 430 },
    routePath: [
      { x: 136, y: 430 },
      { x: 244, y: 376 },
      { x: 376, y: 318 },
      { x: 530, y: 280 },
      { x: 680, y: 234 },
      { x: 820, y: 192 },
    ],
    routeNodeSlots: [
      { x: 244, y: 376, radius: 22 },
      { x: 530, y: 280, radius: 24 },
      { x: 820, y: 192, radius: 28 },
    ],
    npcSlots: [{ x: 350, y: 222 }, { x: 704, y: 352 }],
    treasureSlots: [{ x: 246, y: 232 }, { x: 732, y: 326 }],
    encounterSlots: [{ x: 530, y: 392 }],
    obstacles: [{ x: 392, y: 176, w: 118, h: 44 }, { x: 648, y: 300, w: 124, h: 38 }],
  },
  new_valmar_room_of_chaos: {
    walkBounds: { x: 104, y: 176, w: 796, h: 292 },
    spawn: { x: 202, y: 424 },
    routePath: [
      { x: 202, y: 424 },
      { x: 308, y: 358 },
      { x: 430, y: 300 },
      { x: 572, y: 252 },
      { x: 720, y: 212 },
    ],
    routeNodeSlots: [
      { x: 308, y: 358, radius: 22 },
      { x: 572, y: 252, radius: 24 },
      { x: 720, y: 212, radius: 28 },
    ],
    npcSlots: [{ x: 428, y: 222 }],
    treasureSlots: [{ x: 686, y: 334 }],
    encounterSlots: [{ x: 540, y: 392 }],
    obstacles: [{ x: 426, y: 176, w: 120, h: 40 }],
  },
  new_valmar_core: {
    walkBounds: { x: 128, y: 182, w: 740, h: 280 },
    spawn: { x: 220, y: 426 },
    routePath: [
      { x: 220, y: 426 },
      { x: 328, y: 348 },
      { x: 452, y: 292 },
      { x: 594, y: 238 },
      { x: 720, y: 198 },
    ],
    routeNodeSlots: [
      { x: 328, y: 348, radius: 22 },
      { x: 594, y: 238, radius: 24 },
      { x: 720, y: 198, radius: 28 },
    ],
    npcSlots: [{ x: 452, y: 224 }],
    treasureSlots: [{ x: 690, y: 334 }],
    encounterSlots: [{ x: 560, y: 392 }],
    obstacles: [{ x: 430, y: 180, w: 122, h: 40 }],
  },
};

export const WORLD_LOCATIONS = {
  witt_forest: loc('witt_forest', {
    title: 'Witt Forest',
    type: FIELD,
    region: 'South Silesia',
    chapterIds: ['chapter_1'],
    major: true,
    description: 'Лесная дорога, по которой Рюдо идёт к Карбо в самом начале приключения.',
    exits: ['carbo_village'],
    facilities: ['save-point'],
  }),
  carbo_village: loc('carbo_village', {
    title: 'Carbo Village',
    type: TOWN,
    region: 'South Silesia',
    chapterIds: ['chapter_1'],
    major: true,
    description: 'Стартовая деревня с церковью Граноса, постоялым двором, магазином и домами жителей.',
    exits: ['witt_forest', 'black_forest', 'inor_mountains', 'carbo_inn', 'carbo_store', 'carbo_church', 'carbo_house_1', 'carbo_house_2', 'carbo_house_3', 'carbo_house_4'],
    facilities: ['inn', 'shop', 'church', 'homes'],
  }),
  carbo_inn: loc('carbo_inn', {
    title: 'Carbo Inn',
    type: INTERIOR,
    region: 'Carbo Village',
    chapterIds: ['chapter_1'],
    description: 'Постоялый двор, где Кариус даёт первое серьёзное задание.',
    exits: ['carbo_village'],
    facilities: ['inn'],
  }),
  carbo_store: loc('carbo_store', {
    title: 'Carbo General Store',
    type: INTERIOR,
    region: 'Carbo Village',
    chapterIds: ['chapter_1'],
    description: 'Местный магазин с базовыми припасами и учебником боевой системы.',
    exits: ['carbo_village'],
    facilities: ['shop'],
  }),
  carbo_church: loc('carbo_church', {
    title: 'Church of Granas',
    type: INTERIOR,
    region: 'Carbo Village',
    chapterIds: ['chapter_1'],
    description: 'Центр веры Карбо и место, где Рюдо впервые встречает Елену и отца Кариуса.',
    exits: ['carbo_village'],
    facilities: ['church'],
  }),
  carbo_house_1: loc('carbo_house_1', { title: 'Carbo House 1', type: INTERIOR, region: 'Carbo Village', chapterIds: ['chapter_1'], description: 'Обычный дом деревенских жителей.', exits: ['carbo_village'], facilities: ['home'] }),
  carbo_house_2: loc('carbo_house_2', { title: 'Carbo House 2', type: INTERIOR, region: 'Carbo Village', chapterIds: ['chapter_1'], description: 'Ещё один жилой дом с местными слухами о ритуале.', exits: ['carbo_village'], facilities: ['home'] }),
  carbo_house_3: loc('carbo_house_3', { title: 'Carbo House 3', type: INTERIOR, region: 'Carbo Village', chapterIds: ['chapter_1'], description: 'Дом, где можно услышать страхи простых жителей перед тьмой.', exits: ['carbo_village'], facilities: ['home'] }),
  carbo_house_4: loc('carbo_house_4', { title: 'Carbo House 4', type: INTERIOR, region: 'Carbo Village', chapterIds: ['chapter_1'], description: 'Последний из доступных деревенских домов.', exits: ['carbo_village'], facilities: ['home'] }),
  black_forest: loc('black_forest', {
    title: 'The Black Forest',
    type: FIELD,
    region: 'South Silesia',
    chapterIds: ['chapter_1'],
    major: true,
    description: 'Короткая, но опасная лесная дорога между Карбо и башней Гармии.',
    exits: ['carbo_village', 'garmia_tower'],
  }),
  garmia_tower: loc('garmia_tower', {
    title: 'Garmia Tower',
    type: DUNGEON,
    region: 'South Silesia',
    chapterIds: ['chapter_1'],
    major: true,
    description: 'Башня запечатывания, где ритуал рушится и начинается большая катастрофа.',
    exits: ['black_forest', 'garmia_tower_top'],
    facilities: ['save-point'],
  }),
  garmia_tower_top: loc('garmia_tower_top', {
    title: 'Garmia Tower Top Floor',
    type: SPECIAL,
    region: 'Garmia Tower',
    chapterIds: ['chapter_1'],
    description: 'Верхняя площадка башни — место прорыва тьмы и первой катастрофы.',
    exits: ['garmia_tower'],
  }),
  inor_mountains: loc('inor_mountains', {
    title: 'Inor Mountains',
    type: FIELD,
    region: 'South Silesia',
    chapterIds: ['chapter_1'],
    major: true,
    description: 'Горная дорога из Карбо к Агиру, разбитая скалами и кишащая монстрами.',
    exits: ['carbo_village', 'agear_town'],
    facilities: ['save-point', 'camp'],
  }),
  agear_town: loc('agear_town', {
    title: 'Agear Town',
    type: TOWN,
    region: 'South Silesia',
    chapterIds: ['chapter_1'],
    major: true,
    description: 'Разгромленный городок у входа в Дархэмскую пещеру.',
    exits: ['inor_mountains', 'baked_plains', 'agear_inn', 'agear_guard_tent', 'durham_cave_entrance'],
    facilities: ['inn', 'shop', 'cave-gate'],
  }),
  agear_inn: loc('agear_inn', { title: 'Agear Inn', type: INTERIOR, region: 'Agear Town', chapterIds: ['chapter_1'], description: 'Таверна Вайкса, где группа узнаёт про беду с Роаном.', exits: ['agear_town'], facilities: ['inn'] }),
  agear_guard_tent: loc('agear_guard_tent', { title: 'Agear Guards Tent', type: INTERIOR, region: 'Agear Town', chapterIds: ['chapter_1'], description: 'Импровизированный магазин и пункт снабжения на разрушенной окраине.', exits: ['agear_town'], facilities: ['shop'] }),
  durham_cave_entrance: loc('durham_cave_entrance', {
    title: 'Durham Cave',
    type: DUNGEON,
    region: 'South Silesia',
    chapterIds: ['chapter_1'],
    major: true,
    description: 'Пещера, где Roan гонится за медалью, а партию ждёт первое большое чудовище.',
    exits: ['agear_town', 'durham_cave_depths'],
    facilities: ['save-point'],
  }),
  durham_cave_depths: loc('durham_cave_depths', {
    title: 'Durham Cave Depths',
    type: SPECIAL,
    region: 'Durham Cave',
    chapterIds: ['chapter_1'],
    description: 'Глубинная арена с Durham Minotaur.',
    exits: ['durham_cave_entrance'],
  }),
  baked_plains: loc('baked_plains', {
    title: 'Baked Plains',
    type: FIELD,
    region: 'South Silesia',
    chapterIds: ['chapter_1'],
    major: true,
    description: 'Скалистая и раскалённая дорога между Agear и Liligue.',
    exits: ['agear_town', 'liligue_city'],
    facilities: ['save-point', 'camp'],
  }),
  liligue_city: loc('liligue_city', {
    title: 'Liligue City',
    type: TOWN,
    region: 'South Silesia',
    chapterIds: ['chapter_1'],
    major: true,
    description: 'Город инженеров, рынков и храмовых руин под землёй.',
    exits: ['baked_plains', 'liligue_inn', 'liligue_store', 'liligue_engineer_house', 'liligue_gadan_house', 'liligue_church', 'liligue_house_1', 'liligue_house_2', 'liligue_house_3', 'liligue_house_4', 'liligue_cave', 'skyway_station'],
    facilities: ['inn', 'shop', 'church', 'homes', 'skyway'],
  }),
  liligue_inn: loc('liligue_inn', { title: 'Liligue Inn', type: INTERIOR, region: 'Liligue City', chapterIds: ['chapter_1'], description: 'Постоялый двор Лилига.', exits: ['liligue_city'], facilities: ['inn'] }),
  liligue_store: loc('liligue_store', { title: 'Liligue General Store', type: INTERIOR, region: 'Liligue City', chapterIds: ['chapter_1'], description: 'Городской магазин припасов.', exits: ['liligue_city'], facilities: ['shop'] }),
  liligue_engineer_house: loc('liligue_engineer_house', { title: 'Engineers House', type: INTERIOR, region: 'Liligue City', chapterIds: ['chapter_1'], description: 'Дом местных инженеров и разговоров о технике.', exits: ['liligue_city'], facilities: ['house'] }),
  liligue_gadan_house: loc('liligue_gadan_house', { title: 'Gadan House', type: INTERIOR, region: 'Liligue City', chapterIds: ['chapter_1'], description: 'Дом Гадана и важный сюжетный узел вокруг Лилига.', exits: ['liligue_city'], facilities: ['house'] }),
  liligue_church: loc('liligue_church', { title: 'Liligue Church', type: INTERIOR, region: 'Liligue City', chapterIds: ['chapter_1'], description: 'Небольшая церковь на холме.', exits: ['liligue_city'], facilities: ['church'] }),
  liligue_house_1: loc('liligue_house_1', { title: 'Liligue House 1', type: INTERIOR, region: 'Liligue City', chapterIds: ['chapter_1'], description: 'Жилой дом рядом с рыночной частью города.', exits: ['liligue_city'], facilities: ['home'] }),
  liligue_house_2: loc('liligue_house_2', { title: 'Liligue House 2', type: INTERIOR, region: 'Liligue City', chapterIds: ['chapter_1'], description: 'Ещё один жилой дом.', exits: ['liligue_city'], facilities: ['home'] }),
  liligue_house_3: loc('liligue_house_3', { title: 'Liligue House 3', type: INTERIOR, region: 'Liligue City', chapterIds: ['chapter_1'], description: 'Локальный интерьер с бытовыми диалогами.', exits: ['liligue_city'], facilities: ['home'] }),
  liligue_house_4: loc('liligue_house_4', { title: 'Liligue House 4', type: INTERIOR, region: 'Liligue City', chapterIds: ['chapter_1'], description: 'Последний из доступных домов Лилига.', exits: ['liligue_city'], facilities: ['home'] }),
  liligue_cave: loc('liligue_cave', {
    title: 'Liligue Cave',
    type: DUNGEON,
    region: 'South Silesia',
    chapterIds: ['chapter_1'],
    major: true,
    description: 'Пещеры под Лилигом, ведущие к храмовым руинам и Языку Вальмара.',
    exits: ['liligue_city', 'liligue_temple_ruins'],
    facilities: ['save-point'],
  }),
  liligue_temple_ruins: loc('liligue_temple_ruins', {
    title: 'Temple Ruins',
    type: SPECIAL,
    region: 'Liligue Cave',
    chapterIds: ['chapter_1'],
    description: 'Руины, где скрыт Tongue of Valmar.',
    exits: ['liligue_cave'],
  }),
  skyway_station: loc('skyway_station', {
    title: 'Skyway Station',
    type: SPECIAL,
    region: 'Liligue / East Silesia',
    chapterIds: ['chapter_1', 'chapter_2'],
    major: true,
    description: 'Переходной транспортный узел между Лилигом и снежными лесами востока.',
    exits: ['liligue_city', 'lumir_forest'],
    facilities: ['travel-hub'],
  }),
  lumir_forest: loc('lumir_forest', {
    title: 'Lumir Forest',
    type: FIELD,
    region: 'East Silesia',
    chapterIds: ['chapter_2'],
    major: true,
    description: 'Снежный лес за skyway, ведущий к Garden of Dream и Мируме.',
    exits: ['skyway_station', 'garden_of_dream', 'mirumu_village'],
    facilities: ['save-point'],
  }),
  garden_of_dream: loc('garden_of_dream', {
    title: 'Garden of Dream',
    type: SPECIAL,
    region: 'Lumir Forest',
    chapterIds: ['chapter_2'],
    description: 'Таинственный сад, из которого позже уже нельзя вернуться тем же путём.',
    exits: ['lumir_forest'],
  }),
  mirumu_village: loc('mirumu_village', {
    title: 'Mirumu Village',
    type: TOWN,
    region: 'East Silesia',
    chapterIds: ['chapter_2'],
    major: true,
    description: 'Снежная деревня с мостом, домом Сандры, гостиницей и разломом под землёй.',
    exits: ['lumir_forest', 'st_heim_mountains', 'mirumu_inn', 'mirumu_store', 'mirumu_town_hall', 'mirumu_chief_house', 'mirumu_sandra_house', 'mirumu_shed', 'mysterious_fissure'],
    facilities: ['inn', 'shop', 'town-hall', 'homes'],
  }),
  mirumu_inn: loc('mirumu_inn', { title: 'Mirumu Inn', type: INTERIOR, region: 'Mirumu Village', chapterIds: ['chapter_2'], description: 'Таверна Ирины, где группа пережидает снег и видения.', exits: ['mirumu_village'], facilities: ['inn'] }),
  mirumu_store: loc('mirumu_store', { title: 'Mirumu General Store', type: INTERIOR, region: 'Mirumu Village', chapterIds: ['chapter_2'], description: 'Лавка с базовым снаряжением и расходниками.', exits: ['mirumu_village'], facilities: ['shop'] }),
  mirumu_town_hall: loc('mirumu_town_hall', { title: 'Mirumu Town Hall', type: INTERIOR, region: 'Mirumu Village', chapterIds: ['chapter_2'], description: 'Общественный дом, где разворачиваются сцены с Селеной.', exits: ['mirumu_village'], facilities: ['civic'] }),
  mirumu_chief_house: loc('mirumu_chief_house', { title: 'Chiefs House', type: INTERIOR, region: 'Mirumu Village', chapterIds: ['chapter_2'], description: 'Дом старосты, откуда начинаются местные проблемы.', exits: ['mirumu_village'], facilities: ['home'] }),
  mirumu_sandra_house: loc('mirumu_sandra_house', { title: 'Sandras House', type: INTERIOR, region: 'Mirumu Village', chapterIds: ['chapter_2'], description: 'Дом Сандры и Аиры, важный сюжетный интерьер.', exits: ['mirumu_village'], facilities: ['home'] }),
  mirumu_shed: loc('mirumu_shed', { title: 'Mirumu Shed', type: INTERIOR, region: 'Mirumu Village', chapterIds: ['chapter_2'], description: 'Сарай за домом Сандры, скрывающий путь в глубины.', exits: ['mirumu_village'], facilities: ['shed'] }),
  mysterious_fissure: loc('mysterious_fissure', {
    title: 'Mysterious Fissure',
    type: DUNGEON,
    region: 'East Silesia',
    chapterIds: ['chapter_2'],
    major: true,
    description: 'Разлом под Мирумой, ведущий к порче Аиры.',
    exits: ['mirumu_village', 'fissure_depths'],
    facilities: ['save-point'],
  }),
  fissure_depths: loc('fissure_depths', {
    title: 'Mysterious Fissure Depths',
    type: SPECIAL,
    region: 'Mysterious Fissure',
    chapterIds: ['chapter_2'],
    description: 'Глубинная часть разлома, где открывается путь в душу Аиры.',
    exits: ['mysterious_fissure', 'aira_space'],
  }),
  aira_space: loc('aira_space', {
    title: "Aira's Space",
    type: SPECIAL,
    region: 'Dreamworld',
    chapterIds: ['chapter_2'],
    major: true,
    description: 'Сюжетная сюрреалистическая область внутри боли и памяти Аиры.',
    exits: ['fissure_depths', 'mirumu_village'],
    facilities: ['save-point'],
  }),
  st_heim_mountains: loc('st_heim_mountains', {
    title: 'St. Heim Mountains',
    type: FIELD,
    region: 'East Silesia',
    chapterIds: ['chapter_2'],
    major: true,
    description: 'Длинный горный подъём к папскому государству.',
    exits: ['mirumu_village', 'st_heim_papal_state'],
    facilities: ['camp', 'save-point'],
  }),
  st_heim_papal_state: loc('st_heim_papal_state', {
    title: 'St. Heim Papal State',
    type: TOWN,
    region: 'Holy City',
    chapterIds: ['chapter_2', 'chapter_4'],
    major: true,
    description: 'Священный город с собором, гостиницей, библиотекой и политическим центром церкви.',
    exits: ['st_heim_mountains', 'pilgrim_road', 'st_heim_inn', 'st_heim_store', 'st_heim_bakery', 'st_heim_library', 'st_heim_cathedral_lobby', 'st_heim_guestroom', 'st_heim_balcony', 'st_heim_pasture'],
    facilities: ['inn', 'shop', 'library', 'cathedral', 'pasture'],
  }),
  st_heim_inn: loc('st_heim_inn', { title: 'St. Heim Inn', type: INTERIOR, region: 'St. Heim Papal State', chapterIds: ['chapter_2', 'chapter_4'], description: 'Главная гостиница священного города.', exits: ['st_heim_papal_state'], facilities: ['inn'] }),
  st_heim_store: loc('st_heim_store', { title: 'St. Heim General Store', type: INTERIOR, region: 'St. Heim Papal State', chapterIds: ['chapter_2', 'chapter_4'], description: 'Магазин столицы церкви.', exits: ['st_heim_papal_state'], facilities: ['shop'] }),
  st_heim_bakery: loc('st_heim_bakery', { title: 'St. Heim Bakery', type: INTERIOR, region: 'St. Heim Papal State', chapterIds: ['chapter_2', 'chapter_4'], description: 'Пекарня — небо́льшая, но характерная подлокация города.', exits: ['st_heim_papal_state'], facilities: ['bakery'] }),
  st_heim_library: loc('st_heim_library', { title: 'St. Heim Library', type: INTERIOR, region: 'St. Heim Papal State', chapterIds: ['chapter_2', 'chapter_4'], description: 'Библиотека и источник лора о Граносе и Вальмаре.', exits: ['st_heim_papal_state', 'st_heim_guestroom'], facilities: ['library'] }),
  st_heim_guestroom: loc('st_heim_guestroom', { title: 'Cathedral Guestroom', type: INTERIOR, region: 'St. Heim Papal State', chapterIds: ['chapter_2', 'chapter_4'], description: 'Гостевая комната при соборе.', exits: ['st_heim_papal_state', 'st_heim_library'], facilities: ['inn', 'save-point'] }),
  st_heim_balcony: loc('st_heim_balcony', { title: 'Cathedral Balcony', type: INTERIOR, region: 'St. Heim Papal State', chapterIds: ['chapter_2', 'chapter_4'], description: 'Балкон собора, где часто происходят личные сцены.', exits: ['st_heim_papal_state', 'st_heim_cathedral_lobby'], facilities: ['viewpoint'] }),
  st_heim_cathedral_lobby: loc('st_heim_cathedral_lobby', {
    title: 'Granas Cathedral Lobby',
    type: INTERIOR,
    region: 'St. Heim Papal State',
    chapterIds: ['chapter_2', 'chapter_4'],
    description: 'Главный вход в собор и переход к Audience Chamber, библиотеке и балкону.',
    exits: ['st_heim_papal_state', 'st_heim_audience_chamber', 'st_heim_library', 'st_heim_balcony'],
    facilities: ['cathedral'],
  }),
  st_heim_audience_chamber: loc('st_heim_audience_chamber', {
    title: 'Audience Chamber',
    type: INTERIOR,
    region: 'Granas Cathedral',
    chapterIds: ['chapter_2', 'chapter_4'],
    description: 'Зал аудиенций папы Зеры.',
    exits: ['st_heim_cathedral_lobby', 'zera_room', 'st_heim_forbidden_room'],
    facilities: ['civic'],
  }),
  zera_room: loc('zera_room', { title: 'Pope Zeras Room', type: INTERIOR, region: 'Granas Cathedral', chapterIds: ['chapter_2', 'chapter_4'], description: 'Личный кабинет Зеры.', exits: ['st_heim_audience_chamber'], facilities: ['story'] }),
  st_heim_forbidden_room: loc('st_heim_forbidden_room', { title: 'Forbidden Room', type: SPECIAL, region: 'Granas Cathedral', chapterIds: ['chapter_4'], description: 'Запретная комната и поздний сюжетный узел церкви.', exits: ['st_heim_audience_chamber', 'valmars_moon'], facilities: ['story'] }),
  st_heim_pasture: loc('st_heim_pasture', { title: 'Squeak-Baa Pasture', type: SPECIAL, region: 'St. Heim Papal State', chapterIds: ['chapter_2'], description: 'Небольшая дополнительная зона за гостиницей.', exits: ['st_heim_papal_state'], facilities: ['pasture'] }),
  pilgrim_road: loc('pilgrim_road', {
    title: 'Pilgrim Road',
    type: FIELD,
    region: 'East Silesia',
    chapterIds: ['chapter_2'],
    major: true,
    description: 'Дорога паломников из Сент-Хейма к Раул Хиллс.',
    exits: ['st_heim_papal_state', 'raul_hills'],
  }),
  raul_hills: loc('raul_hills', {
    title: 'Raul Hills',
    type: FIELD,
    region: 'East Silesia',
    chapterIds: ['chapter_2', 'chapter_4'],
    major: true,
    description: 'Холмы с развалинами, мостами и боковыми тропами; позже доступны снова как optional area.',
    exits: ['pilgrim_road', 'cyrum_kingdom', 'cyrum_kingdom_south', 'raul_hills_special'],
    facilities: ['save-point'],
  }),
  raul_hills_special: loc('raul_hills_special', {
    title: 'Raul Hills Special Stage',
    type: DUNGEON,
    region: 'East Silesia',
    chapterIds: ['chapter_4'],
    major: true,
    description: 'Скрытая часть лабиринта Раул Хиллс, открывающаяся при повторном визите: башня с сокровищами, редкие чудовища и Яйцо Феи.',
    exits: ['raul_hills'],
    facilities: ['save-point', 'camp'],
  }),
  cyrum_kingdom: loc('cyrum_kingdom', {
    title: 'Cyrum Kingdom',
    type: TOWN,
    region: 'East Silesia',
    chapterIds: ['chapter_2', 'chapter_4'],
    major: true,
    description: 'Большой город с замком, площадью, гостиницей, портом и скрытым проходом вглубь дворца.',
    exits: ['raul_hills', 'cyrum_inn', 'cyrum_store', 'cyrum_house_1', 'cyrum_house_2', 'cyrum_house_3', 'cyrum_house_4', 'cyrum_castle_square', 'hemble_tent', 'cyrum_port', 'cyrum_secret_passage', 'cyrum_kings_chamber', 'cyrum_kingdom_south'],
    facilities: ['inn', 'shop', 'castle', 'port', 'town-square'],
  }),
  cyrum_inn: loc('cyrum_inn', { title: 'Cyrum Inn', type: INTERIOR, region: 'Cyrum Kingdom', chapterIds: ['chapter_2', 'chapter_4'], description: 'Главная гостиница города.', exits: ['cyrum_kingdom'], facilities: ['inn'] }),
  cyrum_store: loc('cyrum_store', { title: 'Cyrum General Store', type: INTERIOR, region: 'Cyrum Kingdom', chapterIds: ['chapter_2', 'chapter_4'], description: 'Магазин припасов и базового снаряжения.', exits: ['cyrum_kingdom'], facilities: ['shop'] }),
  cyrum_house_1: loc('cyrum_house_1', { title: 'Cyrum House 1', type: INTERIOR, region: 'Cyrum Kingdom', chapterIds: ['chapter_2', 'chapter_4'], description: 'Жилой дом рядом с центральной площадью.', exits: ['cyrum_kingdom'], facilities: ['home'] }),
  cyrum_house_2: loc('cyrum_house_2', { title: 'Cyrum House 2', type: INTERIOR, region: 'Cyrum Kingdom', chapterIds: ['chapter_2', 'chapter_4'], description: 'Жилой интерьер царского города.', exits: ['cyrum_kingdom'], facilities: ['home'] }),
  cyrum_house_3: loc('cyrum_house_3', { title: 'Cyrum House 3', type: INTERIOR, region: 'Cyrum Kingdom', chapterIds: ['chapter_2', 'chapter_4'], description: 'Ещё один городской дом.', exits: ['cyrum_kingdom'], facilities: ['home'] }),
  cyrum_house_4: loc('cyrum_house_4', { title: 'Cyrum House 4', type: INTERIOR, region: 'Cyrum Kingdom', chapterIds: ['chapter_2', 'chapter_4'], description: 'Четвёртый дом и дополнительный flavour.', exits: ['cyrum_kingdom'], facilities: ['home'] }),
  cyrum_castle_square: loc('cyrum_castle_square', { title: 'Castle Square', type: INTERIOR, region: 'Cyrum Kingdom', chapterIds: ['chapter_2', 'chapter_4'], description: 'Площадь у замка, центр местных сцен и разговоров.', exits: ['cyrum_kingdom', 'hemble_tent'], facilities: ['square'] }),
  hemble_tent: loc('hemble_tent', { title: 'Hemble Tent', type: INTERIOR, region: 'Cyrum Kingdom', chapterIds: ['chapter_2'], description: 'Палатка с мини-ивентом arm wrestling и фестивальной атмосферой.', exits: ['cyrum_castle_square'], facilities: ['event'] }),
  cyrum_port: loc('cyrum_port', { title: 'Cyrum Port', type: SPECIAL, region: 'Cyrum Kingdom', chapterIds: ['chapter_2', 'chapter_3'], description: 'Порт, где стоит корабль 50/50.', exits: ['cyrum_kingdom', 'boat_50_50'], facilities: ['port'] }),
  cyrum_secret_passage: loc('cyrum_secret_passage', {
    title: 'Cyrum Castle Secret Passage',
    type: DUNGEON,
    region: 'Cyrum Castle',
    chapterIds: ['chapter_2'],
    major: true,
    description: 'Скрытый проход к тёмной правде под замком Цайрума.',
    exits: ['cyrum_kingdom', 'underground_plant'],
    facilities: ['save-point'],
  }),
  underground_plant: loc('underground_plant', {
    title: 'Underground Plant',
    type: DUNGEON,
    region: 'Cyrum Castle',
    chapterIds: ['chapter_2'],
    major: true,
    description: 'Техноданж с трубами, терминалами и Claws of Valmar.',
    exits: ['cyrum_secret_passage', 'underground_control_room'],
    facilities: ['save-point'],
  }),
  underground_control_room: loc('underground_control_room', {
    title: 'Underground Control Room',
    type: SPECIAL,
    region: 'Underground Plant',
    chapterIds: ['chapter_2'],
    description: 'Финальный отсек подземного завода.',
    exits: ['underground_plant'],
  }),
  cyrum_kings_chamber: loc('cyrum_kings_chamber', { title: 'Kings Chamber', type: INTERIOR, region: 'Cyrum Castle', chapterIds: ['chapter_2', 'chapter_4'], description: 'Покои правителя и один из важных узлов линии Роана.', exits: ['cyrum_kingdom'], facilities: ['story'] }),
  boat_50_50: loc('boat_50_50', {
    title: 'Boat 50/50',
    type: SPECIAL,
    region: 'Sea Route',
    chapterIds: ['chapter_2', 'chapter_3'],
    major: true,
    description: 'Корабль капитана Бакалы между Цайрумом и рифом.',
    exits: ['cyrum_port', 'ceceile_reef'],
    facilities: ['travel-hub'],
  }),
  ceceile_reef: loc('ceceile_reef', {
    title: 'Ceceile Reef',
    type: FIELD,
    region: 'Sea Route',
    chapterIds: ['chapter_3'],
    major: true,
    description: 'Коралловый риф и проход к острову Гарлан.',
    exits: ['boat_50_50', 'garlan_village'],
    facilities: ['camp', 'save-point'],
  }),
  garlan_village: loc('garlan_village', {
    title: 'Garlan Village',
    type: TOWN,
    region: 'Garlan Island',
    chapterIds: ['chapter_3'],
    major: true,
    description: 'Родная деревня Рюдо: таверна, дом самого Рюдо, могилы и дом старосты.',
    exits: ['ceceile_reef', 'grail_mountain', 'garlan_inn', 'garlan_store', 'garlan_chief_house', 'ryudo_house', 'garlan_tombs'],
    facilities: ['inn', 'shop', 'homes', 'graveyard'],
  }),
  garlan_inn: loc('garlan_inn', { title: 'Garlan Inn', type: INTERIOR, region: 'Garlan Village', chapterIds: ['chapter_3'], description: 'Местный постоялый двор.', exits: ['garlan_village'], facilities: ['inn'] }),
  garlan_store: loc('garlan_store', { title: 'Garlan General Store', type: INTERIOR, region: 'Garlan Village', chapterIds: ['chapter_3'], description: 'Маленький магазин на острове.', exits: ['garlan_village'], facilities: ['shop'] }),
  garlan_chief_house: loc('garlan_chief_house', { title: 'Village Chiefs House', type: INTERIOR, region: 'Garlan Village', chapterIds: ['chapter_3'], description: 'Дом старосты деревни.', exits: ['garlan_village'], facilities: ['home'] }),
  ryudo_house: loc('ryudo_house', { title: 'Ryudos House', type: INTERIOR, region: 'Garlan Village', chapterIds: ['chapter_3'], description: 'Личный дом Рюдо и ключевой интерьер его прошлой жизни.', exits: ['garlan_village'], facilities: ['home'] }),
  garlan_tombs: loc('garlan_tombs', { title: 'Village Tombs', type: SPECIAL, region: 'Garlan Village', chapterIds: ['chapter_3'], description: 'Могилы и память о прошлом деревни.', exits: ['garlan_village'], facilities: ['memorial'] }),
  grail_mountain: loc('grail_mountain', {
    title: 'Grail Mountain',
    type: DUNGEON,
    region: 'Garlan Island',
    chapterIds: ['chapter_3'],
    major: true,
    description: 'Грязные дороги, святилище и маршруты к Мелфису.',
    exits: ['garlan_village', 'plateau_of_memories', 'ghoss_forest_west'],
    facilities: ['save-point'],
  }),
  plateau_of_memories: loc('plateau_of_memories', {
    title: 'Plateau of Memories',
    type: SPECIAL,
    region: 'Grail Mountain',
    chapterIds: ['chapter_3'],
    description: 'Арена личной разборки с Мелфисом.',
    exits: ['grail_mountain'],
  }),
  ghoss_forest_west: loc('ghoss_forest_west', {
    title: 'Ghoss Forest West',
    type: FIELD,
    region: 'Northern Route',
    chapterIds: ['chapter_3'],
    major: true,
    description: 'Западная часть лесов по пути к Нанану.',
    exits: ['grail_mountain', 'nanan_village'],
  }),
  nanan_village: loc('nanan_village', {
    title: 'Nanan Village',
    type: TOWN,
    region: 'Northern Route',
    chapterIds: ['chapter_3'],
    major: true,
    description: 'Деревня Марега и последний населённый пункт перед Великим Разломом.',
    exits: ['ghoss_forest_west', 'ghoss_forest_east', 'great_rift', 'nanan_inn', 'nanan_store'],
    facilities: ['inn', 'shop'],
  }),
  nanan_inn: loc('nanan_inn', { title: 'Nanan Inn', type: INTERIOR, region: 'Nanan Village', chapterIds: ['chapter_3'], description: 'Место отдыха и разговоров перед Разломом.', exits: ['nanan_village'], facilities: ['inn'] }),
  nanan_store: loc('nanan_store', { title: 'Nanan General Store', type: INTERIOR, region: 'Nanan Village', chapterIds: ['chapter_3'], description: 'Лавка дальнего северного поселения.', exits: ['nanan_village'], facilities: ['shop'] }),
  ghoss_forest_east: loc('ghoss_forest_east', {
    title: 'Ghoss Forest East',
    type: FIELD,
    region: 'Northern Route',
    chapterIds: ['chapter_3'],
    major: true,
    description: 'Восточная часть лесов перед Великим Разломом.',
    exits: ['nanan_village', 'great_rift'],
  }),
  great_rift: loc('great_rift', {
    title: 'The Great Rift',
    type: DUNGEON,
    region: 'Northern Route',
    chapterIds: ['chapter_3'],
    major: true,
    description: 'Огромная разломная зона перед древним механизмом Демонового Закона.',
    exits: ['ghoss_forest_east', 'nanan_village', 'demons_law'],
    facilities: ['save-point'],
  }),
  demons_law: loc('demons_law', {
    title: "Demon's Law",
    type: DUNGEON,
    region: 'Ancient Mechanism',
    chapterIds: ['chapter_3'],
    major: true,
    description: 'Контрольный комплекс, связанный с путём к Гранасаберу.',
    exits: ['great_rift', 'valmar_body'],
    facilities: ['save-point'],
  }),
  valmar_body: loc('valmar_body', {
    title: "Valmar's Body",
    type: DUNGEON,
    region: 'Ancient Horror',
    chapterIds: ['chapter_3'],
    major: true,
    description: 'Живая плоть Вальмара и один из самых чужеродных late-midgame данжей.',
    exits: ['demons_law', 'st_heim_papal_state'],
    facilities: ['save-point'],
  }),
  valmars_moon: loc('valmars_moon', {
    title: "Valmar's Moon",
    type: DUNGEON,
    region: 'Endgame',
    chapterIds: ['chapter_4'],
    major: true,
    description: 'Лунная биомеханическая крепость с длинным штурмом и финальной ценой.',
    exits: ['st_heim_forbidden_room', 'valmars_womb', 'cyrum_kingdom_south'],
    facilities: ['save-point'],
  }),
  valmars_womb: loc('valmars_womb', {
    title: "Valmar's Womb",
    type: SPECIAL,
    region: "Valmar's Moon",
    chapterIds: ['chapter_4'],
    description: 'Внутренний узел Луны Вальмара, связанный с ключевым сюжетным боем.',
    exits: ['valmars_moon'],
  }),
  cyrum_kingdom_south: loc('cyrum_kingdom_south', {
    title: 'Cyrum Kingdom South',
    type: FIELD,
    region: 'Endgame Front',
    chapterIds: ['chapter_4'],
    major: true,
    description: 'Южный фронт Цайрума в поздней игре.',
    exits: ['valmars_moon', 'raul_hills', 'cyrum_kingdom', 'birthplace_of_the_gods'],
    facilities: ['camp'],
  }),
  birthplace_of_the_gods: loc('birthplace_of_the_gods', {
    title: 'Birthplace of the Gods',
    type: DUNGEON,
    region: 'Ancient Core',
    chapterIds: ['chapter_4'],
    major: true,
    description: 'Космический древний комплекс, где разрушается официальная теология мира.',
    exits: ['cyrum_kingdom_south', 'inner_trial', 'new_valmar'],
    facilities: ['save-point'],
  }),
  inner_trial: loc('inner_trial', {
    title: "Ryudo's Inner Trial",
    type: SPECIAL,
    region: 'Birthplace of the Gods',
    chapterIds: ['chapter_4'],
    description: 'Изолированное внутреннее испытание Рюдо.',
    exits: ['birthplace_of_the_gods'],
  }),
  new_valmar: loc('new_valmar', {
    title: 'New Valmar',
    type: DUNGEON,
    region: 'Final Dungeon',
    chapterIds: ['chapter_4'],
    major: true,
    description: 'Финальный данж, живой и лживый одновременно.',
    exits: ['birthplace_of_the_gods', 'new_valmar_room_of_chaos', 'new_valmar_core'],
    facilities: ['save-point'],
  }),
  new_valmar_room_of_chaos: loc('new_valmar_room_of_chaos', {
    title: 'Room of Chaos',
    type: SPECIAL,
    region: 'New Valmar',
    chapterIds: ['chapter_4'],
    description: 'Ключевой late-game узел иллюзий и обмана Зеры.',
    exits: ['new_valmar'],
  }),
  new_valmar_core: loc('new_valmar_core', {
    title: 'New Valmar Core',
    type: SPECIAL,
    region: 'New Valmar',
    chapterIds: ['chapter_4'],
    description: 'Ядро Нового Вальмара и место финальной развязки.',
    exits: ['new_valmar'],
  }),
};

export const BEAT_WORLD_BINDINGS = {
  carbo_contract: {
    chapterId: 'chapter_1',
    startLocationId: 'witt_forest',
    objectiveLocationId: 'carbo_village',
    battleLocationId: 'carbo_village',
    endLocationId: 'carbo_village',
    route: ['witt_forest', 'carbo_village', 'carbo_church'],
    travelBrief: 'Дойди до Карбо, встреться с Кариусом и Еленой, осмотрись в деревне и приготовь первый шаг escort-маршрута.',
  },
  garmia_failure: {
    chapterId: 'chapter_1',
    startLocationId: 'carbo_village',
    objectiveLocationId: 'garmia_tower_top',
    battleLocationId: 'garmia_tower_top',
    endLocationId: 'carbo_village',
    route: ['carbo_village', 'black_forest', 'garmia_tower', 'garmia_tower_top'],
    travelBrief: 'Проберись через Black Forest и поднимись на верхний этаж башни Гармии.',
  },
  millenia_first_attack: {
    chapterId: 'chapter_1',
    startLocationId: 'carbo_village',
    objectiveLocationId: 'carbo_inn',
    battleLocationId: 'carbo_village',
    endLocationId: 'carbo_village',
    route: ['carbo_village', 'carbo_inn'],
    travelBrief: 'Осмотрись в Карбо после катастрофы и переживи ночную атаку Миллении.',
  },
  agear_roan: {
    chapterId: 'chapter_1',
    startLocationId: 'inor_mountains',
    objectiveLocationId: 'durham_cave_depths',
    battleLocationId: 'durham_cave_depths',
    endLocationId: 'agear_town',
    route: ['inor_mountains', 'agear_town', 'durham_cave_entrance', 'durham_cave_depths'],
    travelBrief: 'Поднимиcь через горы, доберись до Агира и спустись вглубь Durham Cave за Роаном.',
  },
  liligue_and_mareg: {
    chapterId: 'chapter_1',
    startLocationId: 'baked_plains',
    objectiveLocationId: 'liligue_temple_ruins',
    battleLocationId: 'liligue_temple_ruins',
    endLocationId: 'liligue_city',
    route: ['baked_plains', 'liligue_city', 'liligue_cave', 'liligue_temple_ruins'],
    travelBrief: 'Дойди до Лилига и через пещеры доберись до храмовых руин под городом.',
  },
  st_heim_zera: {
    chapterId: 'chapter_2',
    startLocationId: 'lumir_forest',
    objectiveLocationId: 'st_heim_audience_chamber',
    battleLocationId: 'st_heim_audience_chamber',
    endLocationId: 'st_heim_papal_state',
    route: ['lumir_forest', 'mirumu_village', 'st_heim_mountains', 'st_heim_papal_state', 'st_heim_cathedral_lobby', 'st_heim_audience_chamber'],
    travelBrief: 'Пройди через Люмир и Мируму, затем доберись до аудиенционного зала Зеры.',
  },
  cyrum_and_claws: {
    chapterId: 'chapter_2',
    startLocationId: 'st_heim_papal_state',
    objectiveLocationId: 'underground_control_room',
    battleLocationId: 'underground_control_room',
    endLocationId: 'cyrum_kingdom',
    route: ['st_heim_papal_state', 'pilgrim_road', 'raul_hills', 'cyrum_kingdom', 'cyrum_secret_passage', 'underground_plant', 'underground_control_room'],
    travelBrief: 'Покинь Сент-Хейм, перейди Раул Хиллс и вскрой подземный завод Цайрума.',
  },
  garlan_return: {
    chapterId: 'chapter_3',
    startLocationId: 'ceceile_reef',
    objectiveLocationId: 'garlan_village',
    battleLocationId: 'garlan_village',
    endLocationId: 'garlan_village',
    route: ['ceceile_reef', 'garlan_village', 'ryudo_house'],
    travelBrief: 'Переживи Ceceile Reef и вернись в Гарлан, пройдя через дом Рюдо, холод жителей и тяжёлую деревенскую ночь.',
  },
  melfice_duel: {
    chapterId: 'chapter_3',
    startLocationId: 'garlan_village',
    objectiveLocationId: 'plateau_of_memories',
    battleLocationId: 'plateau_of_memories',
    endLocationId: 'grail_mountain',
    route: ['garlan_village', 'grail_mountain', 'plateau_of_memories'],
    travelBrief: 'Поднимись на Grail Mountain и дойди до Plateau of Memories.',
  },
  nanan_and_cyclone: {
    chapterId: 'chapter_3',
    startLocationId: 'ghoss_forest_west',
    objectiveLocationId: 'great_rift',
    battleLocationId: 'great_rift',
    endLocationId: 'nanan_village',
    route: ['ghoss_forest_west', 'nanan_village', 'ghoss_forest_east', 'great_rift'],
    travelBrief: 'Через лес Ghoss дойди до Нанана и затем к Великому Разлому.',
  },
  granasaber_ship: {
    chapterId: 'chapter_3',
    startLocationId: 'great_rift',
    objectiveLocationId: 'demons_law',
    battleLocationId: 'valmar_body',
    endLocationId: 'valmar_body',
    route: ['great_rift', 'demons_law', 'valmar_body'],
    travelBrief: 'Прорвись через Demons Law и затем в Тело Вальмара.',
  },
  cathedral_massacre: {
    chapterId: 'chapter_4',
    startLocationId: 'st_heim_papal_state',
    objectiveLocationId: 'st_heim_cathedral_lobby',
    battleLocationId: 'st_heim_cathedral_lobby',
    endLocationId: 'st_heim_papal_state',
    route: ['st_heim_papal_state', 'st_heim_cathedral_lobby'],
    travelBrief: 'Вернись в Сент-Хейм и войди в собор, где всё начинает рушиться.',
  },
  zera_revealed: {
    chapterId: 'chapter_4',
    startLocationId: 'st_heim_cathedral_lobby',
    objectiveLocationId: 'st_heim_forbidden_room',
    battleLocationId: 'st_heim_forbidden_room',
    endLocationId: 'st_heim_papal_state',
    route: ['st_heim_cathedral_lobby', 'st_heim_audience_chamber', 'st_heim_forbidden_room'],
    travelBrief: 'Поднимись через внутренние помещения собора к запретной комнате.',
  },
  moon_assault: {
    chapterId: 'chapter_4',
    startLocationId: 'st_heim_papal_state',
    objectiveLocationId: 'valmars_womb',
    battleLocationId: 'valmars_womb',
    endLocationId: 'valmars_moon',
    route: ['st_heim_papal_state', 'st_heim_forbidden_room', 'valmars_moon', 'valmars_womb'],
    travelBrief: 'Через катастрофу Сент-Хейма доберись до Луны Вальмара и её внутреннего узла.',
  },
  cyrum_defense: {
    chapterId: 'chapter_4',
    startLocationId: 'cyrum_kingdom_south',
    objectiveLocationId: 'cyrum_kingdom',
    battleLocationId: 'cyrum_kingdom_south',
    endLocationId: 'cyrum_kingdom',
    route: ['cyrum_kingdom_south', 'cyrum_kingdom'],
    travelBrief: 'Удержи южный подход и пробейся обратно в Цайрум.',
  },
  birthplace_descent: {
    chapterId: 'chapter_4',
    startLocationId: 'cyrum_kingdom_south',
    objectiveLocationId: 'birthplace_of_the_gods',
    battleLocationId: 'birthplace_of_the_gods',
    endLocationId: 'birthplace_of_the_gods',
    route: ['cyrum_kingdom_south', 'birthplace_of_the_gods'],
    travelBrief: 'От фронта Цайрума войди в Birthplace of the Gods.',
  },
  inner_trial: {
    chapterId: 'chapter_4',
    startLocationId: 'birthplace_of_the_gods',
    objectiveLocationId: 'inner_trial',
    battleLocationId: 'inner_trial',
    endLocationId: 'birthplace_of_the_gods',
    route: ['birthplace_of_the_gods', 'inner_trial'],
    travelBrief: 'Углубись в древний комплекс и прими личное испытание Рюдо.',
  },
  zera_inside_valmar: {
    chapterId: 'chapter_4',
    startLocationId: 'birthplace_of_the_gods',
    objectiveLocationId: 'new_valmar_room_of_chaos',
    battleLocationId: 'new_valmar_room_of_chaos',
    endLocationId: 'new_valmar',
    route: ['birthplace_of_the_gods', 'new_valmar', 'new_valmar_room_of_chaos'],
    travelBrief: 'Войди в Новый Вальмар и доберись до Room of Chaos.',
  },
  true_finale: {
    chapterId: 'chapter_4',
    startLocationId: 'new_valmar',
    objectiveLocationId: 'new_valmar_core',
    battleLocationId: 'new_valmar_core',
    endLocationId: 'new_valmar_core',
    route: ['new_valmar', 'new_valmar_core'],
    travelBrief: 'Пройди к самому ядру Нового Вальмара и заверши путь.',
  },
};

export function getWorldLocation(locationId) {
  return WORLD_LOCATIONS[locationId] ?? null;
}

export function getBeatWorldBinding(beatId) {
  return BEAT_WORLD_BINDINGS[beatId] ?? null;
}

export function getWorldChapterByBeatId(beatId) {
  const chapterId = getBeatWorldBinding(beatId)?.chapterId;
  return chapterId ? WORLD_CHAPTERS[chapterId] ?? null : null;
}

export function isLocationOpenForBeat(locationId, beatId) {
  const location = getWorldLocation(locationId);
  const chapterId = getBeatWorldBinding(beatId)?.chapterId;
  if (!location || !chapterId) {
    return false;
  }
  return location.chapterIds.includes(chapterId);
}

export function getAccessibleLocationIdsForBeat(beatId) {
  const chapterId = getBeatWorldBinding(beatId)?.chapterId;
  if (!chapterId) {
    return [];
  }
  return Object.values(WORLD_LOCATIONS)
    .filter((location) => location.chapterIds.includes(chapterId))
    .map((location) => location.id);
}

export function getVisibleExitsForBeat(locationId, beatId) {
  const location = getWorldLocation(locationId);
  if (!location) {
    return [];
  }
  return (location.exits ?? [])
    .filter((exitId) => isLocationOpenForBeat(exitId, beatId))
    .map((exitId) => getWorldLocation(exitId))
    .filter(Boolean);
}

export function listMajorLocationsForBeat(beatId) {
  return getAccessibleLocationIdsForBeat(beatId)
    .map((locationId) => getWorldLocation(locationId))
    .filter((location) => location?.major)
    .sort((left, right) => left.title.localeCompare(right.title));
}
